INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aaron', 'Aaberg', 34, '429 High Noon Street Frederick', 'Memphis', 'UT', 463924398);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aaron', 'Aaby', 24, '6 Walnutwood Avenue Hopewell', 'Henderson', 'TX', 697089874);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Abbey', 'Aadland', 80, '7601 Warren Dr. Rolling Meadows', 'Hialeah', 'MO', 692500306);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Abbie', 'Aagaard', 9, '23 Border Street Jeffersonville', 'Boise', 'UT', 662505671);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Abby', 'Aakre', 18, '301 Canterbury Dr. Nashville', 'Washington', 'NJ', 793169326);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Abdul', 'Aaland', 85, '922 Broad Drive Maspeth', 'Aurora', 'OR', 879015143);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Abe', 'Aalbers', 20, '99 Rockville Dr. Saint Johns', 'Houston', 'MI', 291089505);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Abel', 'Aalderink', 6, '769 East George St. Roanoke Rapids', 'Modesto', 'ID', 354814180);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Abigail', 'Aalund', 81, '8382 Howard Dr. West Fargo', 'Nashville-Davidson', 'TX', 702987433);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Abraham', 'Aamodt', 32, '7185 Fremont St. Whitehall', 'Charlotte', 'KS', 202071948);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Abram', 'Aamot', 12, '7407 Heather Avenue Kernersville', 'Cincinnati', 'OK', 288786355);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ada', 'Aanderud', 24, '9695 Hickory St. Shelton', 'Tucson', 'WV', 406920235);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adah', 'Aanenson', 25, '7172 Galvin St. Fargo', 'Garland', 'KS', 722763001);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adalberto', 'Aanerud', 29, '9815 Pierce Lane Anderson', 'Milwaukee', 'MD', 182419226);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adaline', 'Aarant', 35, '8851 Thompson Court Ringgold', 'Laredo', 'UT', 389550630);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adam', 'Aardema', 29, '351 Birchpond Rd. New Lenox', 'Bakersfield', 'IL', 464378226);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adam', 'Aarestad', 56, '1 Glendale St. Troy', 'Tampa', 'SC', 410388119);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adan', 'Aarhus', 90, '27 Piper Road Hammonton', 'Omaha', 'IA', 906387901);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Addie', 'Aaron', 19, '87 Pierce Street Lynnwood', 'Cincinnati', 'FL', 134245444);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adela', 'Aarons', 73, '10 Gates St. Montgomery', 'Dallas', 'OH', 532526456);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adelaida', 'Aaronson', 74, '870 Gartner Ave. West Deptford', 'Wichita', 'AK', 396759839);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adelaide', 'Aarsvold', 50, '21 Valley Farms Lane Crawfordsville', 'Aurora', 'PA', 773617330);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adele', 'Aas', 81, '9094 Gartner St. Rome', 'Toledo', 'HI', 482947949);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adelia', 'Aasby', 12, '8860 Carson Street Hopkins', 'Fort Wayne', 'ID', 642523975);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adelina', 'Aase', 99, '9017 Cedarwood Drive Willingboro', 'New York', 'CT', 724756888);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adeline', 'Aasen', 53, '541 Saxton St. San Jose', 'Columbus', 'WY', 753800397);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adell', 'Aavang', 37, '339 Franklin Ave. Piscataway', 'Oakland', 'WI', 569233634);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adella', 'Abad', 28, '7717 Canterbury St. Reno', 'Omaha', 'PA', 410206101);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adelle', 'Abadi', 62, '398 Rock Maple St. Clifton Park', 'Wichita', 'KY', 687205817);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adena', 'Abadie', 59, '9900 Court Rd. Pasadena', 'Baltimore', 'WY', 701254512);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adina', 'Abair', 55, '7820 E. Windfall Road Solon', 'Arlington', 'SC', 972507786);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adolfo', 'Abaja', 39, '7739 Church Ave. Uniontown', 'North Hempstead', 'WI', 200046231);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adolph', 'Abajian', 1, '8239 Peninsula St. Great Falls', 'Newark', 'HI', 614613811);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adria', 'Abalos', 67, '9103 East Fremont Avenue Portage', 'Sacramento', 'WI', 358645677);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adrian', 'Abaloz', 88, '648 West Street Goldsboro', 'Washington', 'UT', 126563642);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adrian', 'Abar', 21, '74 Broad Ave. South Richmond Hill', 'Chesapeake', 'NC', 859886128);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adriana', 'Abarca', 4, '1 Lake Street Everett', 'Chicago', 'WY', 367703501);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adriane', 'Abare', 57, '874 Amerige Drive Culpeper', 'Fort Worth', 'NH', 825028448);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adrianna', 'Abascal', 62, '9357 St Margarets Street Saratoga Springs', 'Milwaukee', 'ND', 301683477);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adrianne', 'Abasta', 96, '50 County St. Voorhees', 'Anchorage', 'PA', 669072230);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adrien', 'Abate', 79, '89 Willow Street Jamestown', 'Boise', 'OK', 665657615);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adriene', 'Abati', 24, '9072 E. Shub Farm Street Canonsburg', 'Chula Vista', 'CO', 570421372);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Adrienne', 'Abatiell', 86, '9818 Fairfield Dr. Middle Village', 'Laredo', 'MI', 594302040);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Afton', 'Abato', 89, '432 King Court North Bergen', 'Bakersfield', 'AL', 575514742);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Agatha', 'Abatti', 42, '856 West Sunbeam Avenue Youngstown', 'Plano', 'SC', 355954204);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Agnes', 'Abaunza', 3, '200 Hilldale Dr. Beltsville', 'Cleveland', 'RI', 745492083);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Agnus', 'Abaya', 68, '32 Arnold Drive Erlanger', 'Glendale', 'NY', 729442465);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Agripina', 'Abbadessa', 12, '2 Mayflower Court Wake Forest', 'Sacramento', 'WY', 560794381);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Agueda', 'Abbamonte', 80, '158 Cooper Dr. Billerica', 'Akron', 'TX', 595907730);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Agustin', 'Abbas', 79, '8309B Beech Street Rock Hill', 'Anaheim', 'AR', 637064676);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Agustina', 'Abbasi', 63, '347 John St. Vienna', 'Lubbock', 'LA', 480655908);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ahmad', 'Abbassi', 78, '67 Helen Avenue Mesa', 'St. Louis', 'CA', 762700866);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ahmed', 'Abbate', 67, '7625 Airport St. Front Royal', 'San Jose', 'VA', 334442482);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ai', 'Abbatiello', 29, '8760 Alton Avenue North Haven', 'Anaheim', 'NE', 702940100);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aida', 'Abbay', 67, '9610 Whitemarsh Street Palm Harbor', 'Virginia Beach', 'ME', 523407628);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aide', 'Abbe', 63, '641 North Heather St. Bethpage', 'Omaha', 'NE', 649207850);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aiko', 'Abbed', 11, '233 North Sussex Court Spring Hill', 'Pittsburgh', 'ID', 573255226);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aileen', 'Abbenante', 72, '571 West Roberts Ave. Addison', 'Virginia Beach', 'NV', 245605575);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ailene', 'Abbey', 82, '90 North Carson Lane Morrisville', 'Milwaukee', 'CO', 566875628);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aimee', 'Abbinanti', 52, '926 Cherry St. Winder', 'Jersey City', 'CO', 140032251);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aisha', 'Abbington', 88, '56 Homewood Drive Lewiston', 'Newark', 'MN', 595902760);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aja', 'Abbitt', 23, '9528 Foxrun Lane Sumter', 'San Bernardino', 'HI', 455002569);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Akiko', 'Abbot', 3, '8446 Beach St. Mokena', 'Long Beach', 'TN', 244195697);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Akilah', 'Abbott', 94, '608 Bayberry Ave. Norman', 'New Orleans', 'WA', 114075889);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Al', 'Abboud', 94, '53 Cedar Swamp Rd. Redondo Beach', 'Baton Rouge', 'MS', 523943468);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alaina', 'Abbruzzese', 15, '7192 Trout Ave. Statesville', 'Charlotte', 'AZ', 848654414);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alaine', 'Abbs', 83, '40 Sunbeam Circle Lorton', 'Jersey City', 'VA', 326451570);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alan', 'Abby', 9, '26 Warren Street Horn Lake', 'Cleveland', 'WA', 644804495);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alana', 'Abdalla', 26, '371 George Lane Irwin', 'Kansas City', 'VA', 336873516);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alane', 'Abdallah', 0, '9793 Tarkiln Hill Rd. Kearny', 'Lubbock', 'KS', 859874619);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alanna', 'Abdel', 96, '1 Summer Court North Olmsted', 'Modesto', 'ME', 662194709);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alayna', 'Abdelal', 31, '148 Park Avenue Brockton', 'Henderson', 'NE', 615930760);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alba', 'Abdelaziz', 87, '829 Santa Clara Ave. Suwanee', 'Glendale', 'VA', 380718694);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Albert', 'Abdeldayen', 88, '995 Summer Dr. Hudsonville', 'Sacramento', 'CT', 453085300);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Albert', 'Abdelhamid', 79, '37 Beacon St. Clinton Township', 'Garland', 'IL', 503199327);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alberta', 'Abdella', 35, '7342 Greenrose St. Ocean Springs', 'Dallas', 'MN', 519119557);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Albertha', 'Abdelmuti', 9, '87 Race Rd. Milwaukee', 'Charlotte', 'AZ', 874986093);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Albertina', 'Abdelrahman', 50, '8 Surrey Road Mansfield', 'Charlotte', 'MI', 301451218);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Albertine', 'Abdelwahed', 1, '9725 Carpenter Drive Mechanicsburg', 'Stockton', 'AK', 298729284);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alberto', 'Abdi', 16, '7126 Queen Street Panama City', 'Lexington-Fayette', 'AK', 474785727);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Albina', 'Abdin', 17, '164 Winchester St. Hermitage', 'Boise', 'OH', 811581286);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alda', 'Abdo', 87, '316 Sussex Street Sebastian', 'Oakland', 'NH', 122774228);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alden', 'Abdon', 68, '8023 Vernon Road Garner', 'Albuquerque', 'NH', 629139341);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aldo', 'Abdool', 48, '538 W. 6th Lane Cranford', 'Garland', 'HI', 598357846);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alease', 'Abdou', 77, '3 Pendergast Dr. Arlington Heights', 'Detroit', 'WI', 606738270);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alec', 'Abdul', 22, '41 Orange Ave. Riverdale', 'Las Vegas', 'KS', 939895800);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alecia', 'Abdula', 39, '9759 Lancaster Ave. Palmetto', 'San Francisco', 'AL', 851039351);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aleen', 'Abdulaziz', 93, '9747 Shirley St. New Bedford', 'Los Angeles', 'MN', 186343583);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aleida', 'Abdulkarim', 23, '816 Lincoln Dr. Marquette', 'Boston', 'KS', 966026803);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aleisha', 'Abdulla', 45, '7791 Indian Spring Rd. Deerfield', 'Columbus', 'WY', 711967935);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alejandra', 'Abdullah', 39, '9094 Piper Avenue Powell', 'San Jose', 'TN', 553285142);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alejandrina', 'Abdullai', 25, '9 San Pablo St. Brooklyn', 'St. Petersburg', 'CA', 298237444);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alejandro', 'Abdulmateen', 48, '268 Ashley St. Mountain View', 'Santa Ana', 'VT', 177439308);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alena', 'Abdulmuniem', 67, '164 Lake Court Nicholasville', 'Mesa', 'OK', 455250266);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alene', 'Abdur', 80, '6 Constitution St. Cedar Rapids', 'St. Paul', 'KS', 750989370);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alesha', 'Abe', 65, '59 Winding Way St. Garfield', 'Tulsa', 'IL', 520910099);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aleshia', 'Abeb', 30, '16 N. Washington Lane Greensburg', 'Washington', 'NE', 573202575);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alesia', 'Abed', 39, '8099 Overlook Road Greenville', 'Cincinnati', 'MS', 363592785);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alessandra', 'Abedelah', 8, '7557 N. Hillcrest Street Hicksville', 'Los Angeles', 'VT', 677177745);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aleta', 'Abedi', 86, '9888 Miller Ave. Gaithersburg', 'Phoenix', 'IA', 794147876);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aletha', 'Abee', 7, '7428 Foster St. State College', 'Greensboro', 'NV', 999090209);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alethea', 'Abegg', 91, '9065 College St. Massapequa Park', 'Portland', 'KS', 320640458);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alethia', 'Abeita', 4, '8886 East Whitemarsh Rd. Racine', 'Orlando', 'NH', 713894151);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alex', 'Abel', 84, '34 S. Carriage Street Redondo Beach', 'Denver', 'VA', 401004470);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alex', 'Abela', 84, '8581 Willow Court Honolulu', 'Glendale', 'ID', 111848595);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alexa', 'Abelar', 94, '858 Adams St. Starkville', 'Phoenix', 'KY', 863562750);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alexander', 'Abelardo', 98, '510 Kirkland St. Sterling', 'Tulsa', 'MO', 363453327);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alexander', 'Abele', 40, '82 Cross Street Colonial Heights', 'Los Angeles', 'MI', 267605068);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alexandra', 'Abeles', 56, '7096 Sheffield St. York', 'Milwaukee', 'ID', 968232214);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alexandria', 'Abell', 94, '854 E. Nut Swamp Dr. Lincoln Park', 'San Francisco', 'OK', 677414153);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alexia', 'Abella', 29, '136 Sierra Court Olive Branch', 'Las Vegas', 'CA', 926780328);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alexis', 'Abellera', 69, '37 Branch Drive Norristown', 'Akron', 'SD', 831377589);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alexis', 'Abelman', 40, '44 South Brickell St. Reading', 'Kansas City', 'AR', 987592354);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alfonso', 'Abeln', 75, '8320 Sage St. Nampa', 'Miami', 'WA', 223249144);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alfonzo', 'Abels', 1, '542 Queen St. Lincoln', 'Wichita', 'NE', 465027583);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alfred', 'Abelson', 70, '6 East Augusta Dr. Neenah', 'Nashville-Davidson', 'ME', 867794680);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alfreda', 'Aben', 46, '7130 S. Tallwood Drive Greer', 'North Hempstead', 'NH', 671106867);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alfredia', 'Abend', 5, '177 Durham Ave. Syosset', 'Buffalo', 'ID', 515944903);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alfredo', 'Abendroth', 5, '34 Lake View Court Mebane', 'Greensboro', 'KS', 801276329);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ali', 'Aber', 70, '861 Windsor Dr. Villa Rica', 'Newark', 'WI', 398189899);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ali', 'Abercombie', 25, '36 Annadale St. Apt 31 Canal Winchester', 'Austin', 'VT', 336997408);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alia', 'Abercrombie', 59, '867 Belmont Drive Clarksburg', 'Wichita', 'NE', 744002844);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alica', 'Aberle', 27, '8070 Adams St. Norwalk', 'Charlotte', 'MO', 198616336);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alice', 'Abernatha', 18, '61 Wakehurst Dr. Northville', 'Philadelphia', 'OH', 271452267);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alicia', 'Abernathy', 8, '861 Gainsway Ave. Moses Lake', 'Tampa', 'CA', 619593758);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alida', 'Abernethy', 8, '7875 Lakeview Lane Chelmsford', 'Chandler', 'WA', 390683038);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alina', 'Aberson', 97, '196 SW. Victoria St. Glastonbury', 'Lubbock', 'MA', 483889135);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aline', 'Abes', 69, '780 Fifth Ave. Spartanburg', 'Chandler', 'UT', 820784889);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alisa', 'Abeta', 51, '990 Wintergreen St. West Warwick', 'Riverside', 'NE', 267916244);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alise', 'Abete', 70, '1 Canal Court Brandon', 'Chandler', 'WA', 542062947);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alisha', 'Abetrani', 17, '9422 Surrey Lane Feasterville Trevose', 'Fort Worth', 'AZ', 919631120);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alishia', 'Abeyta', 98, '280 Pulaski Dr. Marlton', 'Boise', 'UT', 801804731);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alisia', 'Abide', 92, '17 Bishop Drive Birmingham', 'Modesto', 'FL', 267023114);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alison', 'Abigantus', 53, '8606 Bridle Drive Hudsonville', 'Boston', 'OH', 856574323);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alissa', 'Abila', 86, '800 Philmont Road Essex', 'Sacramento', 'LA', 997601047);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alita', 'Abilay', 10, '8155 SW. Orange Lane New Baltimore', 'Raleigh', 'ID', 255605737);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alix', 'Abild', 64, '728 Old John Rd. Downingtown', 'Las Vegas', 'AL', 249836160);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aliza', 'Abilez', 23, '56 Meadowbrook Street Joliet', 'Pittsburgh', 'GA', 123857767);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alla', 'Abina', 6, '8162 4th Drive Vincentown', 'St. Paul', 'ND', 728889676);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Allan', 'Abington', 7, '7694 Iroquois Dr. Benton Harbor', 'Omaha', 'NJ', 692023552);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alleen', 'Abitong', 26, '481 Vale Dr. Cordova', 'Colorado Springs', 'KY', 678353023);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Allegra', 'Abke', 35, '779 Smoky Hollow Drive Oak Creek', 'Boston', 'UT', 751154619);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Allen', 'Abkemeier', 89, '983 Bayberry St. Derry', 'Glendale', 'VA', 812742342);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Allen', 'Ablang', 83, '324 N. Euclid Lane Mcdonough', 'Chesapeake', 'PA', 332007067);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Allena', 'Ablao', 12, '9712 Linden Ave. Fresh Meadows', 'Kansas City', 'IN', 401116795);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Allene', 'Able', 44, '388 Sunset Ave. Burbank', 'San Antonio', 'AZ', 704256742);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Allie', 'Ableman', 41, '525 Homestead St. Orange Park', 'San Francisco', 'IL', 687599007);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alline', 'Abler', 44, '56 South Richardson St. Torrington', 'Fresno', 'NV', 385724615);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Allison', 'Ables', 82, '64 Maiden Dr. Clifton', 'Tulsa', 'MT', 182279678);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Allyn', 'Ablin', 46, '5 Oak Street Bel Air', 'Rochester', 'IA', 343387977);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Allyson', 'Abling', 4, '17 Fieldstone Ave. Jenison', 'Las Vegas', 'NM', 604834611);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alma', 'Abner', 86, '2 S. Beacon Street Logansport', 'Akron', 'AL', 612363792);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Almeda', 'Abnet', 23, '9 West Warren Lane Forest Hills', 'San Diego', 'ID', 990678098);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Almeta', 'Abney', 94, '7 Railroad St. Sylvania', 'Fresno', 'NJ', 179735932);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alona', 'Abo', 47, '9824 Fremont Ave. Endicott', 'Anaheim', 'IA', 947353926);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alonso', 'Abolafia', 4, '10 Sherwood St. Tacoma', 'Los Angeles', 'RI', 846224585);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alonzo', 'Abolt', 15, '216 San Juan Court Seymour', 'St. Louis', 'RI', 138578322);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alpha', 'Abood', 15, '9501 Woodsman Drive Oak Lawn', 'Stockton', 'KY', 834587718);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alphonse', 'Aboshihata', 22, '7839 Ramblewood Street New Lenox', 'Santa Ana', 'NV', 290186325);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alphonso', 'Aboud', 3, '180 Willow Dr. Cleveland', 'Reno', 'MO', 460910768);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alta', 'Aboudi', 74, '15 White Road Wyandotte', 'Boise', 'UT', 334982013);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Altagracia', 'Aboulahoud', 4, '970 E. Devon Dr. Johnson City', 'Boston', 'NJ', 176724889);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Altha', 'Aboulissan', 25, '7508 Summer Court Altoona', 'Memphis', 'CA', 613794886);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Althea', 'Abousaleh', 98, '7915 Westport Circle Kearny', 'Philadelphia', 'ND', 488489461);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alton', 'Aboytes', 55, '782B Cross St. Hartford', 'El Paso', 'VT', 180104109);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alva', 'Abplanalp', 54, '70 Deerfield Lane Davison', 'Henderson', 'MS', 290177657);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alva', 'Abrachinsky', 34, '93 Trusel Lane Redford', 'Boise', 'WY', 683195679);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alvaro', 'Abraham', 92, '9442 St Louis St. North Tonawanda', 'Chula Vista', 'CO', 236965007);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alvera', 'Abrahamian', 59, '8546 1st Ave. West Bloomfield', 'Lubbock', 'CA', 127877206);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alverta', 'Abrahams', 5, '7838 Buckingham Dr. Dallas', 'Norfolk', 'KS', 432535164);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alvin', 'Abrahamsen', 17, '8138 Lilac Street Ormond Beach', 'Glendale', 'HI', 572595071);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alvina', 'Abrahamson', 93, '9291 Hawthorne Court Warwick', 'Portland', 'IL', 321295233);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alyce', 'Abram', 73, '69 Dogwood Court Tewksbury', 'Cincinnati', 'WY', 739394278);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alycia', 'Abramek', 97, '6 Foster Drive West Fargo', 'Garland', 'NM', 772819523);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alysa', 'Abramian', 72, '9158 Ketch Harbour Dr. Colorado Springs', 'Omaha', 'AZ', 121530095);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alyse', 'Abramoff', 4, '536 N. Evergreen Rd. Stroudsburg', 'San Antonio', 'WI', 855760682);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alysha', 'Abramov', 25, '18 N. Jockey Hollow Street Freehold', 'Fort Worth', 'VT', 611346143);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alysia', 'Abramovich', 52, '209 Livingston Drive Yakima', 'Akron', 'VA', 563890576);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alyson', 'Abramovitz', 51, '467 Philmont Drive Canandaigua', 'Lexington-Fayette', 'PA', 116082656);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Alyssa', 'Abramowitz', 96, '799 Del Monte St. Woodhaven', 'Charlotte', 'IN', 357755004);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amada', 'Abramowski', 63, '703 N. Sunnyslope Avenue Canal Winchester', 'Phoenix', 'TX', 271937796);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amado', 'Abrams', 31, '9917 Country Club Lane Roselle', 'Indianapolis', 'OR', 623978506);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amal', 'Abramson', 14, '8474 Lake Avenue Riverview', 'Madison', 'AL', 751342535);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amalia', 'Abrantes', 37, '8704 Halifax Street Mankato', 'Madison', 'ME', 309017643);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amanda', 'Abreau', 8, '7509 Lexington St. Atlantic City', 'Mesa', 'MD', 990808415);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amber', 'Abrecht', 24, '9526 Bellevue Lane Arvada', 'Jacksonville', 'ID', 795865695);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amberly', 'Abrego', 10, '817 Cobblestone Dr. Christiansburg', 'Santa Ana', 'ND', 648970948);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ambrose', 'Abrell', 38, '10 Ridgewood Lane Round Lake', 'Henderson', 'NV', 289981040);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amee', 'Abreo', 12, '7563 Greystone St. Levittown', 'Newark', 'VA', 233229187);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amelia', 'Abreu', 52, '8345 Sage St. Racine', 'Jacksonville', 'UT', 158113302);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('America', 'Abrev', 28, '993 Westminster Ave. Daphne', 'Chicago', 'IN', 715498643);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ami', 'Abrew', 90, '56 N. Park Dr. Southgate', 'St. Louis', 'VT', 328481901);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amie', 'Abrey', 28, '715 Ashley Dr. West Warwick', 'Denver', 'MA', 176162700);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amiee', 'Abrial', 74, '685 Locust Lane Camp Hill', 'Philadelphia', 'CT', 543101779);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amina', 'Abril', 90, '8738 Bohemia St. Dubuque', 'Akron', 'WY', 826257253);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amira', 'Abriola', 91, '60 Edgefield Lane New Castle', 'Chandler', 'NY', 131987727);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ammie', 'Abrom', 23, '373 East Redwood Circle Hyattsville', 'San Jose', 'MS', 990882518);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amos', 'Abron', 97, '54 Addison Lane Davison', 'Arlington', 'TN', 742808661);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amparo', 'Abruzzese', 91, '606 Hamilton Rd. Forney', 'Chandler', 'IN', 401432404);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Amy', 'Abruzzino', 45, '669 Brewery Rd. Perrysburg', 'Detroit', 'IN', 911729206);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('An', 'Abruzzo', 7, '6 Brook Street Alliance', 'Anchorage', 'ME', 762217631);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ana', 'Absalon', 19, '155 East Grandrose Court Rosemount', 'Wichita', 'MS', 139981010);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anabel', 'Abshear', 67, '8269 South Green Rd. Uniondale', 'Lubbock', 'MO', 413684802);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Analisa', 'Absher', 60, '7664 Monroe St. West Chicago', 'Aurora', 'CO', 967237046);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anamaria', 'Abshier', 78, '97 Oxford Drive Commack', 'Indianapolis', 'NM', 574888997);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anastacia', 'Abshire', 71, '83 Gregory Dr. Clifton', 'Madison', 'CO', 785648884);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anastasia', 'Abson', 36, '157 Olive Ave. Mechanicsville', 'Detroit', 'ME', 353789771);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Andera', 'Abston', 70, '92 Creekside Drive Camas', 'Baltimore', 'ME', 315962348);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anderson', 'Abt', 87, '12 Poor House Lane Perkasie', 'Arlington', 'CO', 308262749);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Andra', 'Abts', 19, '420 Ashley St. Havertown', 'Glendale', 'TX', 418129298);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Andre', 'Abu', 45, '419 Hartford Rd. District Heights', 'Albuquerque', 'NV', 490594964);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Andre', 'Abuaita', 25, '718 Carriage Dr. Titusville', 'Tucson', 'IA', 688552648);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Andrea', 'Abubakr', 57, '574 Canterbury Rd. Springboro', 'Austin', 'SC', 194254569);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Andrea', 'Abud', 89, '7220 Cedar Dr. Stafford', 'Aurora', 'ID', 620905158);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Andreas', 'Abuel', 68, '2 Warren Lane Wellington', 'Jersey City', 'CO', 362065606);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Andree', 'Abugn', 30, '360 Liberty Lane Merrimack', 'San Jose', 'NH', 548419875);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Andres', 'Abuhl', 46, '431 Glenwood Avenue Lorain', 'Fort Worth', 'CT', 906631966);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Andrew', 'Abundis', 76, '7524 Spruce Street Dorchester', 'Mesa', 'VT', 706844030);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Andrew', 'Abundiz', 17, '25 Ohio Street Rocklin', 'Modesto', 'AK', 575055140);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Andria', 'Aburto', 3, '102 Coffee St. Allison Park', 'Santa Ana', 'MA', 804594726);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Andy', 'Abusufait', 51, '4 Lantern Court Tacoma', 'San Antonio', 'NH', 906843549);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anette', 'Acal', 70, '391 Buckingham Street La Crosse', 'Columbus', 'NM', 116598796);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angel', 'Acampora', 26, '606 Lake Forest Street Noblesville', 'Arlington', 'NY', 393442968);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angel', 'Accala', 95, '8486 River Street Bay Shore', 'El Paso', 'OH', 864306277);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angela', 'Accardi', 29, '72 E. Newport Avenue Independence', 'Phoenix', 'OK', 718789613);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angele', 'Accardo', 45, '982 Wild Rose Ave. Montgomery Village', 'Bakersfield', 'WI', 557463423);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angelena', 'Accetta', 14, '33 Grove Court Long Branch', 'Fort Worth', 'OR', 458497812);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angeles', 'Accetturo', 88, '5 Cobblestone Road Nanuet', 'Raleigh', 'DE', 279432377);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angelia', 'Accola', 21, '7054 West Cambridge Court Colorado Springs', 'Baltimore', 'WY', 503956158);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angelic', 'Accomando', 20, '2 Beacon Ave. Wilkes Barre', 'Durham', 'UT', 287897888);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angelica', 'Accornero', 45, '77 Boston Lane Dunedin', 'San Diego', 'WY', 784864341);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angelika', 'Accosta', 47, '394 Kingston Ave. Lansdowne', 'Nashville-Davidson', 'MO', 702525203);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angelina', 'Accurso', 39, '9199 West St. Algonquin', 'St. Paul', 'MA', 775627003);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angeline', 'Ace', 88, '794 Rock Creek Dr. Dundalk', 'Toledo', 'SC', 900146460);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angelique', 'Acebedo', 63, '12 Beaver Ridge Street Murrells Inlet', 'New Orleans', 'NV', 674340764);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angelita', 'Acebo', 22, '343 W. Ketch Harbour Ave. Queensbury', 'Chicago', 'MN', 728114079);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angella', 'Acedo', 93, '96 W. Prince St. Deerfield', 'Tucson', 'ID', 469464313);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angelo', 'Acee', 92, '44 Poor House Street Miami', 'Birmingham', 'MD', 480869605);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angelo', 'Aceituno', 97, '534 S. Marshall Dr. Ottumwa', 'Oklahoma City', 'NY', 504061784);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angelyn', 'Acencio', 67, '9 Richardson Ave. Egg Harbor Township', 'Cincinnati', 'RI', 736411197);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angie', 'Aceret', 65, '7907 Valley Lane Cleveland', 'Tulsa', 'VT', 735790763);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angila', 'Acerno', 60, '7657 Santa Clara St. Union City', 'Lincoln', 'RI', 684397424);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angla', 'Acero', 58, '142 Arcadia Dr. Brookfield', 'Orlando', 'DE', 137995705);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Angle', 'Acerra', 14, '819 Pennsylvania Rd. Adrian', 'Denver', 'ND', 646982788);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anglea', 'Aceto', 53, '711 Mayfield Street Marquette', 'Los Angeles', 'IL', 525460238);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anh', 'Aceuedo', 25, '89 North Constitution Lane Palm Beach Gardens', 'Minneapolis', 'AR', 848404807);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anibal', 'Acevado', 31, '52 Pulaski Lane Sunnyside', 'Omaha', 'LA', 156861493);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anika', 'Aceveda', 93, '176 Wagon Drive Grand Haven', 'Oakland', 'VA', 198539852);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anisa', 'Acevedo', 70, '67 Nichols Rd. Concord', 'Wichita', 'TX', 863257465);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anisha', 'Aceves', 2, '9759 East Broad Drive Dracut', 'Tulsa', 'NV', 724827625);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anissa', 'Acey', 49, '5 Saxton Ave. Stuart', 'Indianapolis', 'MA', 310487813);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anita', 'Acfalle', 54, '4 North Road New Port Richey', 'Aurora', 'CA', 379934661);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anitra', 'Achane', 35, '7002 Mechanic Road Hazleton', 'Wichita', 'ND', 761143642);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anja', 'Ache', 52, '256 Bayberry St. Moses Lake', 'Scottsdale', 'WV', 346077530);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anjanette', 'Acheampong', 94, '9665 Oak Dr. New City', 'San Francisco', 'AL', 429389154);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anjelica', 'Achee', 76, '266 South Hickory Street Santa Clara', 'Colorado Springs', 'SC', 979070011);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ann', 'Achekian', 10, '115 Pheasant St. Lithonia', 'Raleigh', 'AR', 873301176);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anna', 'Achenbach', 7, '133 Pilgrim Ave. Hightstown', 'Columbus', 'WI', 765353443);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annabel', 'Acheson', 21, '7251 New Saddle Dr. Cockeysville', 'Detroit', 'AK', 388530300);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annabell', 'Achille', 39, '7262 Bridge St. Baltimore', 'Philadelphia', 'NJ', 348197915);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annabelle', 'Achilles', 63, '657 Cleveland St. Kennewick', 'Madison', 'ME', 692116667);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annalee', 'Achin', 68, '32 Woodside St. Hallandale', 'Glendale', 'FL', 501522962);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annalisa', 'Achor', 30, '16 Hilltop Street Rockledge', 'Lincoln', 'NC', 147856950);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annamae', 'Achord', 100, '128 Sierra Lane Encino', 'Corpus Christi', 'NE', 532316197);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annamaria', 'Achorn', 23, '7365 East Ivy Street Cockeysville', 'Chicago', 'LA', 542414403);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annamarie', 'Achter', 19, '11 East Woodland Lane Elizabeth City', 'Atlanta', 'UT', 575356262);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anne', 'Achterhof', 44, '7770 North Marlborough Street Middle River', 'Toledo', 'ND', 815909362);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anneliese', 'Achzet', 64, '9138 Winchester Ave. Raleigh', 'Anchorage', 'OR', 402276446);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annelle', 'Achziger', 33, '507 Piper Rd. Clayton', 'St. Paul', 'WV', 989502931);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annemarie', 'Acierno', 33, '220 Richardson Avenue Jamaica Plain', 'Norfolk', 'VT', 663416296);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annett', 'Acimovic', 59, '68 Lancaster St. Nottingham', 'Chula Vista', 'MI', 683451682);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annetta', 'Ack', 68, '7351 N. School Lane Fairburn', 'Anchorage', 'RI', 170072640);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annette', 'Ackah', 22, '9873 Leeton Ridge Dr. Bel Air', 'Houston', 'NC', 509880859);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annice', 'Acken', 53, '8132 Manor Avenue Haines City', 'Riverside', 'OR', 411992387);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annie', 'Acker', 0, '5 Howard Dr. Abingdon', 'Albuquerque', 'ID', 557261961);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annika', 'Ackerley', 93, '441 Gulf Ave. Stuart', 'Jacksonville', 'MD', 749446850);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annis', 'Ackerly', 34, '33 Nichols Road Roslindale', 'Los Angeles', 'RI', 886970293);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annita', 'Ackerman', 76, '37 South Rock Maple Road Ontario', 'St. Paul', 'IN', 506069588);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Annmarie', 'Ackermann', 19, '70 Oakland Street Banning', 'New Orleans', 'SC', 605250978);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anthony', 'Ackers', 37, '44 High Ridge St. Feasterville Trevose', 'Baton Rouge', 'NV', 478404991);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anthony', 'Ackerson', 45, '8490 N. Thorne St. Dunedin', 'Fort Wayne', 'AR', 179265613);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Antione', 'Ackert', 83, '338 Arcadia Ave. Lake Zurich', 'Minneapolis', 'NH', 476954855);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Antionette', 'Ackies', 66, '7328 East Kirkland Drive Green Bay', 'Jersey City', 'NH', 539219833);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Antoine', 'Ackins', 16, '991 West Dr. Brookfield', 'Tucson', 'KS', 232363673);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Antoinette', 'Ackison', 89, '9160 Iroquois Lane Middleton', 'Huntington', 'OH', 725316790);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anton', 'Ackiss', 80, '8256 Henry Avenue Rego Park', 'Philadelphia', 'PA', 847206638);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Antone', 'Ackland', 17, '7520 Hamilton Ave. Jupiter', 'Dallas', 'IA', 863102409);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Antonetta', 'Acklen', 61, '7592 Tower St. Hixson', 'Baton Rouge', 'TX', 897540108);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Antonette', 'Ackles', 16, '330 W. Shore St. Helena', 'Atlanta', 'MO', 676173084);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Antonia', 'Ackley', 74, '724 Nut Swamp Lane Baldwin', 'Hialeah', 'MN', 631049439);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Antonia', 'Acklin', 88, '9198 South Pineknoll Road Navarre', 'Portland', 'NJ', 142279433);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Antonietta', 'Ackman', 31, '71 Cobblestone Ave. Owatonna', 'Tulsa', 'ME', 431892427);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Antonina', 'Ackmann', 51, '473 Old Academy Dr. Winter Haven', 'Anaheim', 'IA', 584004002);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Antonio', 'Ackroyd', 42, '753 E. Shore Lane Newburgh', 'Scottsdale', 'MT', 388166563);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Antonio', 'Acly', 77, '8421 Annadale Dr. Torrance', 'Omaha', 'MI', 770507378);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Antony', 'Acoba', 27, '62 Van Dyke St. Montgomery Village', 'Phoenix', 'TN', 765708451);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Antwan', 'Acocella', 100, '74 Laurel Court Fairfield', 'Chicago', 'MA', 548519806);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Anya', 'Acock', 45, '7413 Lafayette Street Altamonte Springs', 'Tucson', 'MN', 281337887);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Apolonia', 'Acoff', 87, '7415 Union Drive Mesa', 'El Paso', 'NH', 124252752);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('April', 'Acor', 33, '7046 Van Dyke Avenue Grandville', 'St. Louis', 'OK', 400981902);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Apryl', 'Acord', 82, '7763 Church Ave. Santa Cruz', 'Stockton', 'AZ', 338257069);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ara', 'Acorda', 10, '88 Hudson Ave. Point Pleasant Beach', 'Arlington', 'CO', 504493548);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Araceli', 'Acors', 71, '129 S. Walt Whitman Drive Chapel Hill', 'Jacksonville', 'IN', 383489328);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aracelis', 'Acosta', 91, '46 Walnut Street Oak Lawn', 'Boise', 'AL', 897383449);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aracely', 'Acosto', 52, '823 Virginia Drive Arlington Heights', 'Denver', 'NE', 838585638);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arcelia', 'Acothley', 64, '74 Virginia Ave. Ravenna', 'Dallas', 'AL', 397070093);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Archie', 'Acquaviva', 73, '902 Shady Rd. Tullahoma', 'Durham', 'NH', 686885666);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ardath', 'Acquilla', 24, '489 Rock Maple Court Lockport', 'Boise', 'VA', 311891833);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ardelia', 'Acre', 12, '8970 Essex Ave. Winchester', 'Chicago', 'GA', 592502518);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ardell', 'Acree', 20, '9655 Pilgrim Street Massillon', 'Detroit', 'MO', 936632430);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ardella', 'Acres', 99, '67 Tallwood Lane Metairie', 'Santa Ana', 'DE', 978034147);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ardelle', 'Acrey', 33, '9196 South Fremont Court Fullerton', 'St. Petersburg', 'MA', 474931314);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arden', 'Acri', 73, '9479 Newcastle Ave. Newport News', 'Fort Worth', 'MD', 601622063);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ardis', 'Acron', 86, '7350 Devon Ave. Mount Airy', 'Los Angeles', 'IN', 695984376);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ardith', 'Actis', 84, '8685 Marconi Court Elmont', 'Raleigh', 'KS', 531697104);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aretha', 'Acton', 46, '268 Oklahoma St. Owosso', 'Montgomery', 'ND', 333379942);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Argelia', 'Acuff', 62, '7210 SE. Wrangler St. Wilmington', 'Milwaukee', 'DE', 535091924);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Argentina', 'Acuna', 2, '130 Race Avenue New Kensington', 'Tampa', 'HI', 821438549);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ariana', 'Acy', 47, '8534 East Sulphur Springs Ave. Roswell', 'Montgomery', 'WV', 175204777);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ariane', 'Ada', 43, '8528 6th Court Waterbury', 'St. Petersburg', 'ME', 615768492);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arianna', 'Adachi', 49, '7248 Homestead Ave. Chambersburg', 'Jersey City', 'AL', 837985122);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arianne', 'Adair', 28, '7277 Plumb Branch Rd. Mishawaka', 'Orlando', 'WY', 457156818);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arica', 'Adalja', 27, '376 St Paul St. Terre Haute', 'Chula Vista', 'RI', 173956930);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arie', 'Adam', 28, '8839 Monroe Street Patchogue', 'Kansas City', 'CO', 826946331);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ariel', 'Adamaitis', 27, '971 Prince Ave. Avon Lake', 'Minneapolis', 'IL', 419178940);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ariel', 'Adamcik', 52, '7887 Thomas Street Utica', 'Montgomery', 'AK', 948640596);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arielle', 'Adamczak', 89, '7378 Van Dyke Ave. Cincinnati', 'Lincoln', 'WI', 163254985);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arla', 'Adamczyk', 78, '780 Depot Drive Hallandale', 'San Antonio', 'IL', 828561013);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arlean', 'Adame', 18, '764 Oak Meadow Street Bettendorf', 'Denver', 'TN', 175136190);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arleen', 'Adamec', 22, '547 East Rocky River Avenue Wellington', 'Pittsburgh', 'VT', 477319790);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arlen', 'Adamek', 42, '5 New Rd. Oxford', 'Wichita', 'SD', 343231601);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arlena', 'Adames', 86, '9360 Pheasant St. Clarkston', 'Albuquerque', 'VA', 301957120);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arlene', 'Adami', 24, '24 West Clay Circle Griffin', 'Bakersfield', 'FL', 792134223);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arletha', 'Adamiak', 30, '9302 Myers Lane Solon', 'Fort Wayne', 'VT', 933061654);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arletta', 'Adamik', 72, '139 Smith Dr. Boynton Beach', 'Arlington', 'NJ', 514390690);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arlette', 'Adamis', 65, '424 Big Rock Cove St. Front Royal', 'Corpus Christi', 'LA', 805977784);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arlie', 'Adamitis', 91, '353 Stillwater Ave. Blackwood', 'Washington', 'LA', 155640225);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arlinda', 'Adamo', 25, '902 Acacia Street Forest Hills', 'Henderson', 'SC', 903887293);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arline', 'Adamos', 58, '634 Philmont Court Rosedale', 'North Hempstead', 'VA', 768653351);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arlyne', 'Adamowski', 76, '21 River St. North Attleboro', 'Chula Vista', 'AK', 444761949);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Armand', 'Adams', 22, '9292 Hudson Lane York', 'Henderson', 'WA', 256772334);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Armanda', 'Adamsen', 71, '123 SW. Jennings St. Billings', 'Las Vegas', 'WA', 346834296);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Armandina', 'Adamski', 52, '540 North Stonybrook Street Dearborn', 'Lexington-Fayette', 'AR', 321587144);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Armando', 'Adamsky', 45, '554 North Forest Lane Tampa', 'Raleigh', 'MT', 180921895);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Armida', 'Adamson', 33, '7439 Division Drive Torrance', 'Raleigh', 'NJ', 155026026);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arminda', 'Adamsonis', 86, '46 South Court Dr. Graham', 'Washington', 'NJ', 283745467);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arnetta', 'Adamyan', 53, '19 Warren Street Cockeysville', 'Fresno', 'LA', 781535836);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arnette', 'Adan', 60, '895 Clinton Lane San Angelo', 'Cincinnati', 'WY', 772976582);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arnita', 'Adank', 92, '9689 Sheffield Ave. Berwyn', 'Pittsburgh', 'AK', 901326090);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arnold', 'Adas', 90, '8206 Forest St. Traverse City', 'Mesa', 'KS', 425365707);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arnoldo', 'Adauto', 52, '7111 La Sierra Ave. Lemont', 'San Jose', 'WA', 164435592);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arnulfo', 'Adaway', 22, '65 Linda Street Mount Prospect', 'Dallas', 'NE', 319125345);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aron', 'Aday', 81, '108 Rockaway Street Auburndale', 'Milwaukee', 'CA', 200886335);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arron', 'Adcock', 86, '23 Bohemia Rd. Toms River', 'Omaha', 'DE', 207986046);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Art', 'Adcox', 100, '92 Brook St. Los Banos', 'Henderson', 'CA', 909985102);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arthur', 'Addair', 10, '465 Summerhouse Street Melbourne', 'Orlando', 'AZ', 279746982);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arthur', 'Addams', 10, '92 Harvey Street Whitehall', 'Washington', 'ME', 152323683);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Artie', 'Addario', 15, '2 Hillside Court Upper Darby', 'Riverside', 'IN', 414463569);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arturo', 'Addeo', 96, '941 Fawn Drive Clover', 'Pittsburgh', 'NE', 638698919);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Arvilla', 'Adderley', 49, '315 Plymouth Drive Long Beach', 'Las Vegas', 'UT', 839555389);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Asa', 'Adderly', 15, '8 Country St. Farmingdale', 'San Diego', 'IN', 408742365);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Asha', 'Addesso', 61, '8209 Walnut Street Decatur', 'Rochester', 'WA', 264771606);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ashanti', 'Addicks', 19, '8 Studebaker Road Danbury', 'Arlington', 'SC', 551628746);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ashely', 'Addie', 38, '194 Helen Avenue Queensbury', 'Baton Rouge', 'UT', 998302456);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ashlea', 'Addiego', 71, '975 Edgewater St. Parkersburg', 'Lubbock', 'AR', 932212123);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ashlee', 'Addington', 53, '966 Virginia Dr. Orland Park', 'Chesapeake', 'ID', 903799492);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ashleigh', 'Addis', 60, '7903 Lakeshore Drive Ravenna', 'Tulsa', 'VA', 426801783);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ashley', 'Addison', 87, '7862 Euclid Lane Alabaster', 'Omaha', 'ME', 479821837);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ashley', 'Addleman', 98, '309 Wayne Ave. Easley', 'Columbus', 'WV', 416274843);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ashli', 'Addo', 81, '17 Golf Dr. Bay City', 'Charlotte', 'TX', 542106997);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ashlie', 'Adduci', 34, '440 Fairview Street Omaha', 'St. Petersburg', 'MD', 806614180);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ashly', 'Addy', 20, '55 Middle River St. Tucson', 'Montgomery', 'MN', 512204292);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ashlyn', 'Ade', 34, '9718 South Durham Lane Huntersville', 'San Antonio', 'CT', 560981297);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ashton', 'Adebisi', 27, '7054 Rocky River Street Levittown', 'Colorado Springs', 'KY', 598742361);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Asia', 'Adee', 91, '7920 Newbridge Dr. Garden City', 'Arlington', 'FL', 142454328);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Asley', 'Adel', 53, '8061 Thorne Ave. Forney', 'San Bernardino', 'IL', 625590099);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Assunta', 'Adelblue', 41, '63 Lees Creek Court Greenwood', 'Austin', 'RI', 667283443);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Astrid', 'Adelgren', 51, '8169 Applegate St. Davison', 'Charlotte', 'WV', 518182579);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Asuncion', 'Adelizzi', 77, '8849 Miles Drive Olive Branch', 'Long Beach', 'RI', 879517641);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Athena', 'Adell', 76, '444 Rockville Dr. Zeeland', 'Philadelphia', 'OR', 211636966);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aubrey', 'Adelman', 94, '9019 Delaware Street Dekalb', 'Buffalo', 'KS', 894607347);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aubrey', 'Adelmann', 27, '905 Arch Street Hendersonville', 'Hialeah', 'ME', 645965658);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Audie', 'Adelmund', 79, '172 Bridgeton Ave. Wilmington', 'Huntington', 'IL', 757286235);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Audra', 'Adels', 48, '9277 6th Rd. Waltham', 'Arlington', 'MD', 503895627);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Audrea', 'Adelsberg', 0, '29 E. Airport St. Rolla', 'Chandler', 'CO', 767446710);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Audrey', 'Adelson', 33, '41 Valley Farms Avenue Saginaw', 'Phoenix', 'DE', 199251488);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Audria', 'Adelsperger', 80, '3 Lees Creek Ave. Nanuet', 'Atlanta', 'IN', 756043563);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Audrie', 'Adelstein', 27, '9311 North Oklahoma Street Hillsboro', 'Fort Worth', 'HI', 831169037);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Audry', 'Adema', 40, '613 Locust St. Mansfield', 'Nashville-Davidson', 'NE', 899519968);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('August', 'Aden', 15, '135 North Plymouth Ave. Ossining', 'Madison', 'MA', 818078992);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Augusta', 'Adens', 80, '8330 Hudson Rd. Roseville', 'Cincinnati', 'NH', 874335677);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Augustina', 'Ader', 53, '598 North North Street Roanoke Rapids', 'Jacksonville', 'CO', 441790210);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Augustine', 'Aderhold', 98, '344 Arnold Ave. Downers Grove', 'Anchorage', 'ID', 538110664);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Augustine', 'Aderholdt', 23, '707 West Rd. Lake Villa', 'Milwaukee', 'MA', 222552680);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Augustus', 'Aderholt', 85, '499 Nichols Court Kennesaw', 'San Bernardino', 'KS', 403214473);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aundrea', 'Aderman', 63, '372 East Cherry Street Sylvania', 'St. Louis', 'PA', 546663290);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aura', 'Aderson', 66, '8286 East Ridgeview Road Staten Island', 'Jacksonville', 'NE', 753971891);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aurea', 'Ades', 58, '7472 Rosewood Rd. Jamaica', 'Indianapolis', 'MO', 857952950);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aurelia', 'Adessa', 56, '73 Wentworth Street Glasgow', 'Fort Worth', 'CT', 819960014);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aurelio', 'Adesso', 61, '7549 Mayfield Street New Castle', 'Raleigh', 'WI', 300771601);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aurora', 'Adey', 8, '182 N. Smoky Hollow Lane Lincoln', 'Akron', 'LA', 471041593);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Aurore', 'Adeyemo', 52, '7223 Garfield Dr. Holyoke', 'St. Paul', 'GA', 800409293);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Austin', 'Adger', 81, '802 Fulton St. Logansport', 'Buffalo', 'VA', 698241205);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Austin', 'Adham', 97, '36 Grant Dr. Baldwin', 'Jacksonville', 'NJ', 374096503);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Autumn', 'Adhami', 21, '18 Brandywine Dr. Ocean Springs', 'Chula Vista', 'WA', 602908637);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ava', 'Adi', 18, '96 Union Dr. Bristol', 'Los Angeles', 'ID', 887039088);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Avelina', 'Adib', 56, '56 Border Circle Mableton', 'Plano', 'ND', 211164118);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Avery', 'Adickes', 49, '52 Bay Meadows Ave. Douglasville', 'Montgomery', 'MD', 970725803);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Avery', 'Adie', 51, '8783 Dogwood Ave. Tuckerton', 'Toledo', 'FL', 178279126);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Avis', 'Adil', 92, '22 Holly Road Roseville', 'Laredo', 'DE', 335451620);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Avril', 'Adinolfi', 33, '92 Pennington Dr. Niagara Falls', 'Greensboro', 'PA', 404634049);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Awilda', 'Adjei', 70, '7021 Arlington Dr. Lumberton', 'Oklahoma City', 'RI', 484311730);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ayako', 'Adjutant', 76, '7413 Heritage Ave. Fair Lawn', 'Los Angeles', 'PA', 926918630);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ayana', 'Adkerson', 21, '9384 Shirley St. Painesville', 'Lincoln', 'AL', 655708920);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ayanna', 'Adkin', 2, '677 East Ridge Rd. Davison', 'Henderson', 'KY', 810114655);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ayesha', 'Adkins', 42, '618 West Heather Ave. Reading', 'Greensboro', 'MO', 304619848);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Azalee', 'Adkinson', 65, '405 Nut Swamp Ave. Flushing', 'Baltimore', 'HI', 593012614);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Azucena', 'Adkison', 54, '15 Richardson St. Albany', 'Milwaukee', 'MN', 591024411);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Azzie', 'Adkisson', 50, '8243 Thompson Court Danbury', 'Anchorage', 'GA', 453916828);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Babara', 'Adlam', 45, '7373 Woodsman Street Gurnee', 'Montgomery', 'CA', 539856336);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Babette', 'Adle', 6, '9445 Livingston Drive Valrico', 'Greensboro', 'SC', 442049797);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bailey', 'Adleman', 36, '857 S. Poplar Street Jenison', 'Akron', 'OR', 962919729);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bambi', 'Adler', 2, '9658 Tunnel Dr. Winchester', 'Greensboro', 'WI', 771975535);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bao', 'Adley', 31, '34 Market Ave. Rome', 'Cincinnati', 'UT', 810558099);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Barabara', 'Adling', 33, '872 Wild Horse Street Frankfort', 'Montgomery', 'DE', 875368165);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Barb', 'Adloff', 0, '85 Somerset Street Honolulu', 'Garland', 'CA', 119636703);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Barbar', 'Admas', 93, '74 North Branch Street Williamsburg', 'Jersey City', 'AL', 651415102);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Barbara', 'Admire', 49, '62 Stillwater Dr. Round Lake', 'Long Beach', 'ME', 256040818);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Barbera', 'Adner', 45, '9734 Andover St. Strongsville', 'Fort Worth', 'SD', 802487644);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Barbie', 'Adney', 19, '39 Constitution Street Halethorpe', 'Hialeah', 'WA', 595464837);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Barbra', 'Adolf', 5, '96 Carriage Ave. Schaumburg', 'Cincinnati', 'OR', 314358503);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bari', 'Adolfo', 24, '91 Maiden Road Hope Mills', 'Sacramento', 'SC', 199143158);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Barney', 'Adolfson', 52, '66 Brook St. Hinesville', 'Kansas City', 'MT', 232295195);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Barrett', 'Adolph', 45, '372 Purple Finch Ave. Conyers', 'Sacramento', 'AL', 998048230);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Barrie', 'Adolphe', 63, '8 County St. Lincoln Park', 'St. Petersburg', 'VA', 878921501);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Barry', 'Adolphsen', 0, '954 Arlington Dr. Avon Lake', 'Madison', 'ME', 819697245);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bart', 'Adolphson', 42, '9108 E. Nicolls Drive Chandler', 'North Hempstead', 'WI', 443777734);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Barton', 'Adolphus', 96, '937 Dogwood Dr. West Bloomfield', 'Lexington-Fayette', 'CO', 581998140);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Basil', 'Adomaitis', 79, '9 S. Hamilton St. North Fort Myers', 'Jersey City', 'KY', 835869795);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Basilia', 'Adon', 30, '4 South Green Avenue Palatine', 'Laredo', 'KY', 220435971);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bea', 'Adonis', 50, '653 Cobblestone St. Chardon', 'St. Louis', 'ID', 711674113);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Beata', 'Adorno', 96, '9213 Peg Shop St. Marquette', 'San Francisco', 'MO', 479948520);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Beatrice', 'Adragna', 39, '20 Foster Ave. Hagerstown', 'Hialeah', 'OK', 641654636);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Beatris', 'Adrian', 44, '261 Pacific St. Morrisville', 'San Diego', 'AK', 699701091);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Beatriz', 'Adriance', 43, '206 Nut Swamp Ave. Oak Forest', 'Orlando', 'MD', 813712560);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Beau', 'Adriano', 31, '54 Roberts St. Yakima', 'Garland', 'UT', 587500803);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Beaulah', 'Adrid', 100, '2 South Drive Wausau', 'Lexington-Fayette', 'WV', 610063009);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bebe', 'Adrien', 80, '51 Sycamore Drive Oak Ridge', 'Houston', 'MO', 807987030);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Becki', 'Adrion', 69, '898 Livingston Drive Grovetown', 'Indianapolis', 'AR', 439984265);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Beckie', 'Adrovel', 18, '74 Brookside Street Santa Clara', 'Chicago', 'NC', 441680471);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Becky', 'Adside', 1, '643 Mayfair Lane Lakeville', 'Dallas', 'IA', 399254022);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bee', 'Adsit', 73, '8033 Edgewater St. Tucson', 'Scottsdale', 'OK', 349598469);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Belen', 'Adu', 6, '9029 Vine Ave. Elk River', 'Chandler', 'TN', 542587003);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Belia', 'Aduddell', 98, '73 Maple Lane Omaha', 'Wichita', 'KY', 472173496);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Belinda', 'Adule', 91, '55 Morris Ave. Pittsford', 'San Jose', 'OR', 542531732);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Belkis', 'Adwell', 100, '7441 Fifth Drive Batavia', 'Birmingham', 'MS', 274097050);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bell', 'Ady', 19, '231 Edgemont Ave. Millington', 'Los Angeles', 'AK', 219070878);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bella', 'Adzhabakyan', 88, '33 El Dorado Street Jacksonville Beach', 'Tucson', 'UT', 544844999);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Belle', 'Aegerter', 43, '38 East Pleasant Circle Poughkeepsie', 'Sacramento', 'FL', 474421432);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Belva', 'Aeillo', 91, '9859 Gartner Dr. Derby', 'Miami', 'LA', 567339035);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Ben', 'Aeling', 70, '83 Marvon Lane Louisville', 'Scottsdale', 'MN', 788590807);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Benedict', 'Aemmer', 54, '96 Cooper St. Westfield', 'Columbus', 'OH', 310993699);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Benita', 'Aerni', 62, '636 Birchwood St. Glendora', 'Nashville-Davidson', 'NC', 463983048);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Benito', 'Aerts', 60, '77 Green Ave. Gulfport', 'Denver', 'WV', 143214843);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Benjamin', 'Aery', 49, '853 Birch Hill Ave. Elyria', 'St. Petersburg', 'CA', 809545778);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bennett', 'Aeschbacher', 62, '916 Rockwell Street Everett', 'Riverside', 'WI', 352940913);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bennie', 'Aeschliman', 36, '856 Ridge Dr. Newton', 'Anaheim', 'DE', 445520091);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bennie', 'Aeschlimann', 27, '58 Madison Lane Chaska', 'Virginia Beach', 'SD', 135900527);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Benny', 'Afable', 49, '531 Forest St. Redford', 'Cleveland', 'CO', 126752515);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Benton', 'Afalava', 58, '898 Philmont Court Orchard Park', 'Birmingham', 'MD', 461352848);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Berenice', 'Afan', 88, '195 S. Hillcrest St. Ottumwa', 'Seattle', 'KY', 618794179);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Berna', 'Afanador', 60, '11 Stillwater St. Grovetown', 'Charlotte', 'NJ', 739704835);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bernadette', 'Affagato', 9, '58 Santa Clara Rd. Elmhurst', 'Arlington', 'OH', 167914332);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bernadine', 'Affeld', 77, '241 Gonzales St. Anaheim', 'Phoenix', 'CT', 829350003);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bernard', 'Affelt', 0, '7128 Bridle Street West Lafayette', 'St. Petersburg', 'DE', 564762378);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bernarda', 'Affeltranger', 41, '66 Newport Road Gaithersburg', 'Garland', 'IN', 685769001);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bernardina', 'Affleck', 80, '50 Sunbeam Ave. Paramus', 'Honolulu', 'MN', 383911507);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bernardine', 'Afflick', 1, '95 Taylor Street Drexel Hill', 'Austin', 'MI', 463276047);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bernardo', 'Affolter', 13, '6 Pineknoll St. Astoria', 'Buffalo', 'NM', 810357398);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Berneice', 'Affronti', 28, '759 Summerhouse Lane Gainesville', 'Fort Wayne', 'ND', 635185473);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bernetta', 'Aflalo', 60, '4 Madison Lane Banning', 'Hialeah', 'AZ', 741471884);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bernice', 'Afoa', 1, '246 Sunbeam Road Statesville', 'Fort Worth', 'VT', 382926045);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bernie', 'Afonso', 11, '8195 Orange Dr. Utica', 'Columbus', 'FL', 262904110);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bernie', 'Africa', 27, '357 Devon St. Grayslake', 'Arlington', 'ND', 575584106);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Berniece', 'Afshar', 0, '3 Water Lane Maryville', 'Chesapeake', 'ND', 279119051);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bernita', 'Afshari', 52, '8086 East Lower River St. East Orange', 'Las Vegas', 'MD', 191654441);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Berry', 'Afton', 19, '482 Elm Ave. Blacksburg', 'Colorado Springs', 'OH', 202523659);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Berry', 'Afurong', 4, '779 Lawrence St. Marion', 'Akron', 'IN', 306067072);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bert', 'Afzal', 71, '8285 Bridle St. Muskego', 'Los Angeles', 'OR', 871966777);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Berta', 'Agamao', 22, '8954 Trout Street Elmhurst', 'Honolulu', 'AK', 124053870);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bertha', 'Agan', 29, '8850 Beechwood Street Reston', 'Memphis', 'VT', 248955651);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bertie', 'Agans', 91, '774 Rosewood Ave. Wadsworth', 'San Bernardino', 'NC', 466654569);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bertram', 'Agar', 53, '41 Buttonwood St. Germantown', 'Sacramento', 'CA', 904936186);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Beryl', 'Agard', 16, '8757 Belmont St. Fort Washington', 'Omaha', 'NJ', 152879716);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bess', 'Agarwal', 8, '8869 N. Wood Ave. Snohomish', 'Mesa', 'WY', 270261943);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bessie', 'Agbayani', 92, '522 Bow Ridge St. Sidney', 'Cleveland', 'VT', 579737616);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Beth', 'Agbisit', 59, '749 Fairfield St. Wooster', 'Birmingham', 'MN', 794326864);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bethanie', 'Agcaoili', 40, '79 Shipley St. Clermont', 'Washington', 'TN', 485107777);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bethann', 'Age', 19, '97 Devon Rd. Malvern', 'Columbus', 'MS', 418098966);
INSERT INTO Customers (FirstName, LastName, Age, Street, City, State, PhoneNumber) VALUES('Bethany', 'Ageboi', 52, '47 Pulaski Lane Brookline', 'Bakersfield', 'WI', 386345234);
