INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aaron', 'Aaberg', 2, '429 High Noon Street Frederick', 'Tampa', 'MS', 644694921);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aaron', 'Aaby', 64, '6 Walnutwood Avenue Hopewell', 'Portland', 'AL', 268650866);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Abbey', 'Aadland', 64, '7601 Warren Dr. Rolling Meadows', 'Miami', 'ME', 363779145);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Abbie', 'Aagaard', 44, '23 Border Street Jeffersonville', 'Akron', 'OR', 366334948);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Abby', 'Aakre', 9, '301 Canterbury Dr. Nashville', 'Birmingham', 'NY', 239393941);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Abdul', 'Aaland', 53, '922 Broad Drive Maspeth', 'Mesa', 'VT', 353941351);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Abe', 'Aalbers', 63, '99 Rockville Dr. Saint Johns', 'Milwaukee', 'OR', 633860584);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Abel', 'Aalderink', 4, '769 East George St. Roanoke Rapids', 'Aurora', 'IL', 903023800);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Abigail', 'Aalund', 0, '8382 Howard Dr. West Fargo', 'Chandler', 'CA', 348709744);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Abraham', 'Aamodt', 88, '7185 Fremont St. Whitehall', 'Kansas City', 'GA', 906923265);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Abram', 'Aamot', 33, '7407 Heather Avenue Kernersville', 'Greensboro', 'AR', 574265114);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ada', 'Aanderud', 1, '9695 Hickory St. Shelton', 'Phoenix', 'NC', 329657228);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adah', 'Aanenson', 29, '7172 Galvin St. Fargo', 'Chicago', 'IL', 554961875);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adalberto', 'Aanerud', 6, '9815 Pierce Lane Anderson', 'St. Petersburg', 'HI', 494459366);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adaline', 'Aarant', 99, '8851 Thompson Court Ringgold', 'Sacramento', 'DE', 476697040);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adam', 'Aardema', 93, '351 Birchpond Rd. New Lenox', 'Anaheim', 'PA', 706228509);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adam', 'Aarestad', 18, '1 Glendale St. Troy', 'Scottsdale', 'PA', 318453805);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adan', 'Aarhus', 27, '27 Piper Road Hammonton', 'St. Paul', 'MI', 408707381);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Addie', 'Aaron', 84, '87 Pierce Street Lynnwood', 'Anaheim', 'TN', 351053207);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adela', 'Aarons', 16, '10 Gates St. Montgomery', 'Reno', 'PA', 694346578);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adelaida', 'Aaronson', 95, '870 Gartner Ave. West Deptford', 'Jersey City', 'CT', 629287428);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adelaide', 'Aarsvold', 38, '21 Valley Farms Lane Crawfordsville', 'Philadelphia', 'MT', 399073750);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adele', 'Aas', 86, '9094 Gartner St. Rome', 'Houston', 'PA', 158186171);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adelia', 'Aasby', 23, '8860 Carson Street Hopkins', 'Anaheim', 'OR', 773792826);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adelina', 'Aase', 34, '9017 Cedarwood Drive Willingboro', 'Norfolk', 'MS', 656151934);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adeline', 'Aasen', 1, '541 Saxton St. San Jose', 'Laredo', 'AL', 513791704);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adell', 'Aavang', 28, '339 Franklin Ave. Piscataway', 'Oklahoma City', 'NH', 130243203);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adella', 'Abad', 82, '7717 Canterbury St. Reno', 'Honolulu', 'VA', 850895602);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adelle', 'Abadi', 6, '398 Rock Maple St. Clifton Park', 'Riverside', 'IN', 348006160);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adena', 'Abadie', 26, '9900 Court Rd. Pasadena', 'Boston', 'MD', 119632378);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adina', 'Abair', 67, '7820 E. Windfall Road Solon', 'Huntington', 'HI', 469062462);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adolfo', 'Abaja', 28, '7739 Church Ave. Uniontown', 'Miami', 'IA', 170351734);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adolph', 'Abajian', 34, '8239 Peninsula St. Great Falls', 'Memphis', 'WI', 781222281);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adria', 'Abalos', 13, '9103 East Fremont Avenue Portage', 'Lexington-Fayette', 'OK', 294610650);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adrian', 'Abaloz', 18, '648 West Street Goldsboro', 'Hialeah', 'MN', 603721600);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adrian', 'Abar', 2, '74 Broad Ave. South Richmond Hill', 'St. Petersburg', 'LA', 156711996);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adriana', 'Abarca', 48, '1 Lake Street Everett', 'Houston', 'VA', 230589869);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adriane', 'Abare', 94, '874 Amerige Drive Culpeper', 'Milwaukee', 'NE', 515723750);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adrianna', 'Abascal', 68, '9357 St Margarets Street Saratoga Springs', 'Cincinnati', 'SD', 441970009);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adrianne', 'Abasta', 91, '50 County St. Voorhees', 'Norfolk', 'NY', 352589013);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adrien', 'Abate', 86, '89 Willow Street Jamestown', 'Lexington-Fayette', 'NH', 452963448);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adriene', 'Abati', 26, '9072 E. Shub Farm Street Canonsburg', 'El Paso', 'AL', 689233432);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Adrienne', 'Abatiell', 1, '9818 Fairfield Dr. Middle Village', 'Denver', 'MT', 471300110);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Afton', 'Abato', 82, '432 King Court North Bergen', 'St. Paul', 'MI', 804880573);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Agatha', 'Abatti', 35, '856 West Sunbeam Avenue Youngstown', 'St. Louis', 'ND', 426434691);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Agnes', 'Abaunza', 29, '200 Hilldale Dr. Beltsville', 'Phoenix', 'NE', 128953938);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Agnus', 'Abaya', 77, '32 Arnold Drive Erlanger', 'Colorado Springs', 'MN', 762008421);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Agripina', 'Abbadessa', 94, '2 Mayflower Court Wake Forest', 'Akron', 'TN', 406135445);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Agueda', 'Abbamonte', 69, '158 Cooper Dr. Billerica', 'Los Angeles', 'MS', 202153737);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Agustin', 'Abbas', 74, '8309B Beech Street Rock Hill', 'Philadelphia', 'VA', 469762298);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Agustina', 'Abbasi', 57, '347 John St. Vienna', 'Tulsa', 'AR', 847794930);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ahmad', 'Abbassi', 57, '67 Helen Avenue Mesa', 'Tucson', 'IL', 347409595);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ahmed', 'Abbate', 31, '7625 Airport St. Front Royal', 'Hialeah', 'SD', 586736172);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ai', 'Abbatiello', 7, '8760 Alton Avenue North Haven', 'Hialeah', 'MD', 827550434);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aida', 'Abbay', 3, '9610 Whitemarsh Street Palm Harbor', 'Norfolk', 'TX', 384292402);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aide', 'Abbe', 78, '641 North Heather St. Bethpage', 'Norfolk', 'AZ', 324712440);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aiko', 'Abbed', 71, '233 North Sussex Court Spring Hill', 'Bakersfield', 'PA', 990716589);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aileen', 'Abbenante', 91, '571 West Roberts Ave. Addison', 'Plano', 'OK', 806825686);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ailene', 'Abbey', 67, '90 North Carson Lane Morrisville', 'Mesa', 'UT', 411470432);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aimee', 'Abbinanti', 35, '926 Cherry St. Winder', 'Cleveland', 'MO', 613323960);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aisha', 'Abbington', 88, '56 Homewood Drive Lewiston', 'Minneapolis', 'MS', 159475689);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aja', 'Abbitt', 58, '9528 Foxrun Lane Sumter', 'New Orleans', 'RI', 244458959);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Akiko', 'Abbot', 80, '8446 Beach St. Mokena', 'St. Paul', 'WI', 647680392);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Akilah', 'Abbott', 24, '608 Bayberry Ave. Norman', 'Durham', 'PA', 912766063);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Al', 'Abboud', 29, '53 Cedar Swamp Rd. Redondo Beach', 'Charlotte', 'OR', 943372048);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alaina', 'Abbruzzese', 12, '7192 Trout Ave. Statesville', 'Anchorage', 'ND', 794367067);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alaine', 'Abbs', 26, '40 Sunbeam Circle Lorton', 'Houston', 'MN', 703062784);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alan', 'Abby', 86, '26 Warren Street Horn Lake', 'Chesapeake', 'RI', 834661621);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alana', 'Abdalla', 37, '371 George Lane Irwin', 'Indianapolis', 'MT', 688906263);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alane', 'Abdallah', 1, '9793 Tarkiln Hill Rd. Kearny', 'New Orleans', 'OK', 608171454);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alanna', 'Abdel', 56, '1 Summer Court North Olmsted', 'Stockton', 'OR', 590882729);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alayna', 'Abdelal', 5, '148 Park Avenue Brockton', 'El Paso', 'VA', 644377129);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alba', 'Abdelaziz', 86, '829 Santa Clara Ave. Suwanee', 'Chicago', 'TX', 479084249);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Albert', 'Abdeldayen', 29, '995 Summer Dr. Hudsonville', 'Albuquerque', 'AZ', 650228005);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Albert', 'Abdelhamid', 1, '37 Beacon St. Clinton Township', 'Tampa', 'IN', 815655706);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alberta', 'Abdella', 48, '7342 Greenrose St. Ocean Springs', 'Seattle', 'MN', 414931890);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Albertha', 'Abdelmuti', 0, '87 Race Rd. Milwaukee', 'Fort Wayne', 'AL', 724382098);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Albertina', 'Abdelrahman', 35, '8 Surrey Road Mansfield', 'Tulsa', 'IN', 734371550);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Albertine', 'Abdelwahed', 32, '9725 Carpenter Drive Mechanicsburg', 'Mesa', 'MI', 253521567);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alberto', 'Abdi', 79, '7126 Queen Street Panama City', 'Newark', 'IN', 940128127);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Albina', 'Abdin', 99, '164 Winchester St. Hermitage', 'New York', 'WY', 720127768);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alda', 'Abdo', 70, '316 Sussex Street Sebastian', 'Bakersfield', 'CT', 133238931);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alden', 'Abdon', 42, '8023 Vernon Road Garner', 'Charlotte', 'WY', 240940105);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aldo', 'Abdool', 9, '538 W. 6th Lane Cranford', 'Tampa', 'KS', 742537259);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alease', 'Abdou', 54, '3 Pendergast Dr. Arlington Heights', 'Cleveland', 'ID', 432373468);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alec', 'Abdul', 8, '41 Orange Ave. Riverdale', 'Arlington', 'NJ', 958808158);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alecia', 'Abdula', 37, '9759 Lancaster Ave. Palmetto', 'Norfolk', 'WA', 873249737);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aleen', 'Abdulaziz', 62, '9747 Shirley St. New Bedford', 'Omaha', 'TX', 326961399);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aleida', 'Abdulkarim', 5, '816 Lincoln Dr. Marquette', 'Seattle', 'GA', 888304477);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aleisha', 'Abdulla', 46, '7791 Indian Spring Rd. Deerfield', 'Austin', 'NC', 451856938);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alejandra', 'Abdullah', 70, '9094 Piper Avenue Powell', 'Fort Wayne', 'FL', 997715101);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alejandrina', 'Abdullai', 54, '9 San Pablo St. Brooklyn', 'Madison', 'AZ', 657421781);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alejandro', 'Abdulmateen', 91, '268 Ashley St. Mountain View', 'Washington', 'HI', 665649407);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alena', 'Abdulmuniem', 94, '164 Lake Court Nicholasville', 'Seattle', 'WV', 801756709);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alene', 'Abdur', 47, '6 Constitution St. Cedar Rapids', 'Boise', 'CA', 479661638);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alesha', 'Abe', 42, '59 Winding Way St. Garfield', 'Rochester', 'OK', 687926961);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aleshia', 'Abeb', 80, '16 N. Washington Lane Greensburg', 'Baton Rouge', 'LA', 772145664);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alesia', 'Abed', 17, '8099 Overlook Road Greenville', 'Kansas City', 'IL', 324909029);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alessandra', 'Abedelah', 17, '7557 N. Hillcrest Street Hicksville', 'Fresno', 'OR', 565512819);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aleta', 'Abedi', 18, '9888 Miller Ave. Gaithersburg', 'St. Petersburg', 'OH', 305915151);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aletha', 'Abee', 8, '7428 Foster St. State College', 'Dallas', 'TN', 589059776);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alethea', 'Abegg', 81, '9065 College St. Massapequa Park', 'Austin', 'GA', 812699004);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alethia', 'Abeita', 59, '8886 East Whitemarsh Rd. Racine', 'Oakland', 'NY', 613443916);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alex', 'Abel', 0, '34 S. Carriage Street Redondo Beach', 'Miami', 'SD', 811892842);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alex', 'Abela', 7, '8581 Willow Court Honolulu', 'Arlington', 'IN', 383501048);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alexa', 'Abelar', 90, '858 Adams St. Starkville', 'Toledo', 'IA', 623478604);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alexander', 'Abelardo', 90, '510 Kirkland St. Sterling', 'Arlington', 'IA', 401863025);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alexander', 'Abele', 36, '82 Cross Street Colonial Heights', 'New Orleans', 'MD', 603727023);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alexandra', 'Abeles', 79, '7096 Sheffield St. York', 'Tulsa', 'MA', 859495723);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alexandria', 'Abell', 78, '854 E. Nut Swamp Dr. Lincoln Park', 'Fort Worth', 'MD', 430908362);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alexia', 'Abella', 36, '136 Sierra Court Olive Branch', 'St. Petersburg', 'VT', 594263850);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alexis', 'Abellera', 56, '37 Branch Drive Norristown', 'Houston', 'NV', 872904632);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alexis', 'Abelman', 61, '44 South Brickell St. Reading', 'Madison', 'CT', 324738399);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alfonso', 'Abeln', 48, '8320 Sage St. Nampa', 'Tulsa', 'SD', 395269429);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alfonzo', 'Abels', 86, '542 Queen St. Lincoln', 'Tucson', 'MI', 488789264);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alfred', 'Abelson', 47, '6 East Augusta Dr. Neenah', 'Boston', 'NY', 604962731);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alfreda', 'Aben', 46, '7130 S. Tallwood Drive Greer', 'Garland', 'MT', 682585088);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alfredia', 'Abend', 57, '177 Durham Ave. Syosset', 'Long Beach', 'LA', 237876072);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alfredo', 'Abendroth', 94, '34 Lake View Court Mebane', 'Chandler', 'VT', 989050173);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ali', 'Aber', 43, '861 Windsor Dr. Villa Rica', 'St. Petersburg', 'OK', 497412865);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ali', 'Abercombie', 92, '36 Annadale St. Apt 31 Canal Winchester', 'St. Paul', 'ND', 523726887);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alia', 'Abercrombie', 26, '867 Belmont Drive Clarksburg', 'Santa Ana', 'IN', 957328147);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alica', 'Aberle', 32, '8070 Adams St. Norwalk', 'Tampa', 'NJ', 464969237);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alice', 'Abernatha', 21, '61 Wakehurst Dr. Northville', 'Stockton', 'NY', 430207509);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alicia', 'Abernathy', 57, '861 Gainsway Ave. Moses Lake', 'San Diego', 'UT', 665919708);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alida', 'Abernethy', 72, '7875 Lakeview Lane Chelmsford', 'Orlando', 'OH', 554614749);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alina', 'Aberson', 22, '196 SW. Victoria St. Glastonbury', 'Modesto', 'UT', 979521649);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aline', 'Abes', 56, '780 Fifth Ave. Spartanburg', 'Aurora', 'NJ', 830176250);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alisa', 'Abeta', 91, '990 Wintergreen St. West Warwick', 'Minneapolis', 'NY', 654190314);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alise', 'Abete', 38, '1 Canal Court Brandon', 'Sacramento', 'AK', 731140072);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alisha', 'Abetrani', 9, '9422 Surrey Lane Feasterville Trevose', 'San Jose', 'KY', 236781071);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alishia', 'Abeyta', 8, '280 Pulaski Dr. Marlton', 'Glendale', 'MA', 779464278);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alisia', 'Abide', 65, '17 Bishop Drive Birmingham', 'Cincinnati', 'TX', 485184900);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alison', 'Abigantus', 92, '8606 Bridle Drive Hudsonville', 'San Francisco', 'AL', 749461189);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alissa', 'Abila', 60, '800 Philmont Road Essex', 'St. Petersburg', 'AR', 303830263);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alita', 'Abilay', 80, '8155 SW. Orange Lane New Baltimore', 'Miami', 'WY', 653374095);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alix', 'Abild', 74, '728 Old John Rd. Downingtown', 'Virginia Beach', 'ND', 217362951);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aliza', 'Abilez', 87, '56 Meadowbrook Street Joliet', 'Jacksonville', 'IN', 794978676);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alla', 'Abina', 66, '8162 4th Drive Vincentown', 'Toledo', 'AZ', 547703752);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Allan', 'Abington', 17, '7694 Iroquois Dr. Benton Harbor', 'Cincinnati', 'WA', 687233419);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alleen', 'Abitong', 89, '481 Vale Dr. Cordova', 'Plano', 'WY', 881769535);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Allegra', 'Abke', 90, '779 Smoky Hollow Drive Oak Creek', 'Durham', 'NE', 168325730);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Allen', 'Abkemeier', 84, '983 Bayberry St. Derry', 'Corpus Christi', 'ND', 458293064);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Allen', 'Ablang', 87, '324 N. Euclid Lane Mcdonough', 'North Hempstead', 'IN', 410567505);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Allena', 'Ablao', 59, '9712 Linden Ave. Fresh Meadows', 'Boise', 'MI', 556428072);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Allene', 'Able', 51, '388 Sunset Ave. Burbank', 'Phoenix', 'NM', 789680354);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Allie', 'Ableman', 7, '525 Homestead St. Orange Park', 'Miami', 'HI', 822866888);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alline', 'Abler', 47, '56 South Richardson St. Torrington', 'Chandler', 'CT', 274333989);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Allison', 'Ables', 87, '64 Maiden Dr. Clifton', 'Oakland', 'MS', 633916379);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Allyn', 'Ablin', 100, '5 Oak Street Bel Air', 'Anaheim', 'NJ', 403266717);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Allyson', 'Abling', 12, '17 Fieldstone Ave. Jenison', 'Madison', 'VA', 455458520);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alma', 'Abner', 51, '2 S. Beacon Street Logansport', 'Jacksonville', 'MD', 229629469);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Almeda', 'Abnet', 52, '9 West Warren Lane Forest Hills', 'Glendale', 'IL', 206174222);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Almeta', 'Abney', 40, '7 Railroad St. Sylvania', 'Laredo', 'KS', 745148679);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alona', 'Abo', 57, '9824 Fremont Ave. Endicott', 'Jersey City', 'NJ', 796832281);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alonso', 'Abolafia', 75, '10 Sherwood St. Tacoma', 'Tulsa', 'WY', 141414310);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alonzo', 'Abolt', 27, '216 San Juan Court Seymour', 'St. Louis', 'KY', 907270911);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alpha', 'Abood', 12, '9501 Woodsman Drive Oak Lawn', 'Stockton', 'IL', 261524527);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alphonse', 'Aboshihata', 42, '7839 Ramblewood Street New Lenox', 'North Hempstead', 'CA', 946196036);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alphonso', 'Aboud', 11, '180 Willow Dr. Cleveland', 'Wichita', 'AR', 612779949);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alta', 'Aboudi', 59, '15 White Road Wyandotte', 'Honolulu', 'TX', 797105003);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Altagracia', 'Aboulahoud', 50, '970 E. Devon Dr. Johnson City', 'San Francisco', 'AZ', 776089395);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Altha', 'Aboulissan', 35, '7508 Summer Court Altoona', 'Oklahoma City', 'ME', 408625548);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Althea', 'Abousaleh', 62, '7915 Westport Circle Kearny', 'Oakland', 'CO', 673093003);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alton', 'Aboytes', 93, '782B Cross St. Hartford', 'Atlanta', 'FL', 221495552);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alva', 'Abplanalp', 82, '70 Deerfield Lane Davison', 'Oakland', 'NJ', 777412640);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alva', 'Abrachinsky', 4, '93 Trusel Lane Redford', 'Anaheim', 'PA', 791015957);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alvaro', 'Abraham', 92, '9442 St Louis St. North Tonawanda', 'Boston', 'VT', 938797828);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alvera', 'Abrahamian', 96, '8546 1st Ave. West Bloomfield', 'Lubbock', 'WV', 745665423);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alverta', 'Abrahams', 80, '7838 Buckingham Dr. Dallas', 'Austin', 'CA', 762960265);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alvin', 'Abrahamsen', 39, '8138 Lilac Street Ormond Beach', 'San Diego', 'NH', 659893395);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alvina', 'Abrahamson', 45, '9291 Hawthorne Court Warwick', 'Fort Worth', 'CT', 427767068);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alyce', 'Abram', 5, '69 Dogwood Court Tewksbury', 'Montgomery', 'RI', 782158096);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alycia', 'Abramek', 49, '6 Foster Drive West Fargo', 'Sacramento', 'IN', 385400194);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alysa', 'Abramian', 54, '9158 Ketch Harbour Dr. Colorado Springs', 'Bakersfield', 'MN', 189596509);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alyse', 'Abramoff', 10, '536 N. Evergreen Rd. Stroudsburg', 'Lincoln', 'MD', 260012221);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alysha', 'Abramov', 40, '18 N. Jockey Hollow Street Freehold', 'Wichita', 'SC', 498519169);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alysia', 'Abramovich', 31, '209 Livingston Drive Yakima', 'Long Beach', 'RI', 640188993);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alyson', 'Abramovitz', 37, '467 Philmont Drive Canandaigua', 'Norfolk', 'RI', 756181719);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Alyssa', 'Abramowitz', 99, '799 Del Monte St. Woodhaven', 'Columbus', 'ND', 590249573);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amada', 'Abramowski', 100, '703 N. Sunnyslope Avenue Canal Winchester', 'Chesapeake', 'ND', 859525797);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amado', 'Abrams', 9, '9917 Country Club Lane Roselle', 'Orlando', 'WA', 269584919);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amal', 'Abramson', 47, '8474 Lake Avenue Riverview', 'Cleveland', 'CO', 953406187);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amalia', 'Abrantes', 37, '8704 Halifax Street Mankato', 'Hialeah', 'SC', 789962416);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amanda', 'Abreau', 13, '7509 Lexington St. Atlantic City', 'Stockton', 'NC', 134495022);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amber', 'Abrecht', 56, '9526 Bellevue Lane Arvada', 'Dallas', 'ND', 550620482);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amberly', 'Abrego', 5, '817 Cobblestone Dr. Christiansburg', 'Miami', 'KY', 486131565);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ambrose', 'Abrell', 59, '10 Ridgewood Lane Round Lake', 'Anaheim', 'CT', 967308063);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amee', 'Abreo', 38, '7563 Greystone St. Levittown', 'Virginia Beach', 'VA', 175568271);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amelia', 'Abreu', 73, '8345 Sage St. Racine', 'Boise', 'ME', 620876002);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('America', 'Abrev', 0, '993 Westminster Ave. Daphne', 'Norfolk', 'CO', 935795937);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ami', 'Abrew', 59, '56 N. Park Dr. Southgate', 'San Bernardino', 'PA', 877113619);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amie', 'Abrey', 33, '715 Ashley Dr. West Warwick', 'Philadelphia', 'DE', 164051181);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amiee', 'Abrial', 16, '685 Locust Lane Camp Hill', 'Houston', 'CT', 559892456);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amina', 'Abril', 15, '8738 Bohemia St. Dubuque', 'Boston', 'UT', 917987961);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amira', 'Abriola', 62, '60 Edgefield Lane New Castle', 'Wichita', 'IN', 854079894);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ammie', 'Abrom', 58, '373 East Redwood Circle Hyattsville', 'Arlington', 'MD', 826861860);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amos', 'Abron', 14, '54 Addison Lane Davison', 'Atlanta', 'ME', 305968891);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amparo', 'Abruzzese', 1, '606 Hamilton Rd. Forney', 'Memphis', 'UT', 649118288);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Amy', 'Abruzzino', 17, '669 Brewery Rd. Perrysburg', 'Charlotte', 'NH', 671909420);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('An', 'Abruzzo', 58, '6 Brook Street Alliance', 'Garland', 'HI', 992581827);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ana', 'Absalon', 9, '155 East Grandrose Court Rosemount', 'Miami', 'MA', 488990894);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anabel', 'Abshear', 47, '8269 South Green Rd. Uniondale', 'Greensboro', 'IA', 416493277);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Analisa', 'Absher', 83, '7664 Monroe St. West Chicago', 'Sacramento', 'OH', 400908314);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anamaria', 'Abshier', 85, '97 Oxford Drive Commack', 'Chesapeake', 'ME', 507696626);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anastacia', 'Abshire', 1, '83 Gregory Dr. Clifton', 'Nashville-Davidson', 'KS', 861265832);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anastasia', 'Abson', 93, '157 Olive Ave. Mechanicsville', 'Arlington', 'NY', 118584393);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Andera', 'Abston', 84, '92 Creekside Drive Camas', 'Philadelphia', 'SC', 529060244);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anderson', 'Abt', 92, '12 Poor House Lane Perkasie', 'Sacramento', 'CT', 574668132);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Andra', 'Abts', 63, '420 Ashley St. Havertown', 'Dallas', 'IA', 658210381);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Andre', 'Abu', 18, '419 Hartford Rd. District Heights', 'Rochester', 'CO', 708958786);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Andre', 'Abuaita', 37, '718 Carriage Dr. Titusville', 'Tucson', 'KS', 135023930);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Andrea', 'Abubakr', 68, '574 Canterbury Rd. Springboro', 'Atlanta', 'LA', 390276152);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Andrea', 'Abud', 7, '7220 Cedar Dr. Stafford', 'Norfolk', 'OK', 223523685);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Andreas', 'Abuel', 20, '2 Warren Lane Wellington', 'Toledo', 'IL', 715366838);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Andree', 'Abugn', 51, '360 Liberty Lane Merrimack', 'Denver', 'CO', 134886642);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Andres', 'Abuhl', 21, '431 Glenwood Avenue Lorain', 'Washington', 'OR', 368663378);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Andrew', 'Abundis', 32, '7524 Spruce Street Dorchester', 'Dallas', 'MN', 188282536);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Andrew', 'Abundiz', 61, '25 Ohio Street Rocklin', 'St. Paul', 'DE', 850142061);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Andria', 'Aburto', 91, '102 Coffee St. Allison Park', 'Arlington', 'MS', 157350090);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Andy', 'Abusufait', 84, '4 Lantern Court Tacoma', 'Fresno', 'KS', 589675601);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anette', 'Acal', 82, '391 Buckingham Street La Crosse', 'Seattle', 'MS', 697348093);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angel', 'Acampora', 36, '606 Lake Forest Street Noblesville', 'Raleigh', 'PA', 270402957);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angel', 'Accala', 67, '8486 River Street Bay Shore', 'St. Louis', 'MA', 467716362);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angela', 'Accardi', 77, '72 E. Newport Avenue Independence', 'St. Louis', 'CA', 374505646);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angele', 'Accardo', 2, '982 Wild Rose Ave. Montgomery Village', 'Los Angeles', 'LA', 142627179);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angelena', 'Accetta', 91, '33 Grove Court Long Branch', 'Anchorage', 'SC', 228049540);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angeles', 'Accetturo', 48, '5 Cobblestone Road Nanuet', 'Anaheim', 'IN', 209928270);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angelia', 'Accola', 77, '7054 West Cambridge Court Colorado Springs', 'Tampa', 'WY', 781373344);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angelic', 'Accomando', 23, '2 Beacon Ave. Wilkes Barre', 'Chula Vista', 'SD', 946633365);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angelica', 'Accornero', 62, '77 Boston Lane Dunedin', 'Jersey City', 'VA', 844318019);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angelika', 'Accosta', 82, '394 Kingston Ave. Lansdowne', 'Bakersfield', 'GA', 899436210);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angelina', 'Accurso', 74, '9199 West St. Algonquin', 'Chicago', 'NC', 885997590);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angeline', 'Ace', 57, '794 Rock Creek Dr. Dundalk', 'Miami', 'WA', 585825687);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angelique', 'Acebedo', 56, '12 Beaver Ridge Street Murrells Inlet', 'Buffalo', 'MS', 865896520);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angelita', 'Acebo', 75, '343 W. Ketch Harbour Ave. Queensbury', 'Omaha', 'WA', 448876650);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angella', 'Acedo', 35, '96 W. Prince St. Deerfield', 'Lubbock', 'SD', 128341466);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angelo', 'Acee', 70, '44 Poor House Street Miami', 'Reno', 'WY', 387260382);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angelo', 'Aceituno', 78, '534 S. Marshall Dr. Ottumwa', 'Lexington-Fayette', 'HI', 603133776);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angelyn', 'Acencio', 38, '9 Richardson Ave. Egg Harbor Township', 'Henderson', 'MT', 248756301);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angie', 'Aceret', 21, '7907 Valley Lane Cleveland', 'New Orleans', 'VT', 546557424);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angila', 'Acerno', 46, '7657 Santa Clara St. Union City', 'Lincoln', 'ND', 919697049);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angla', 'Acero', 68, '142 Arcadia Dr. Brookfield', 'Detroit', 'MD', 410497672);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Angle', 'Acerra', 6, '819 Pennsylvania Rd. Adrian', 'Virginia Beach', 'SC', 415442302);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anglea', 'Aceto', 75, '711 Mayfield Street Marquette', 'Lincoln', 'OH', 117816544);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anh', 'Aceuedo', 86, '89 North Constitution Lane Palm Beach Gardens', 'Phoenix', 'NH', 516650566);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anibal', 'Acevado', 5, '52 Pulaski Lane Sunnyside', 'Fort Wayne', 'NC', 523268224);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anika', 'Aceveda', 36, '176 Wagon Drive Grand Haven', 'Rochester', 'NC', 534393604);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anisa', 'Acevedo', 38, '67 Nichols Rd. Concord', 'Durham', 'AL', 987105566);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anisha', 'Aceves', 97, '9759 East Broad Drive Dracut', 'Arlington', 'LA', 844683364);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anissa', 'Acey', 67, '5 Saxton Ave. Stuart', 'Birmingham', 'CA', 853213406);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anita', 'Acfalle', 10, '4 North Road New Port Richey', 'Henderson', 'MN', 900106975);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anitra', 'Achane', 1, '7002 Mechanic Road Hazleton', 'Fort Worth', 'MA', 431905254);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anja', 'Ache', 49, '256 Bayberry St. Moses Lake', 'Bakersfield', 'MS', 957295164);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anjanette', 'Acheampong', 64, '9665 Oak Dr. New City', 'Oakland', 'ME', 836583012);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anjelica', 'Achee', 26, '266 South Hickory Street Santa Clara', 'Atlanta', 'IL', 860161757);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ann', 'Achekian', 74, '115 Pheasant St. Lithonia', 'Long Beach', 'CA', 716826527);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anna', 'Achenbach', 33, '133 Pilgrim Ave. Hightstown', 'Colorado Springs', 'IL', 825000836);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annabel', 'Acheson', 53, '7251 New Saddle Dr. Cockeysville', 'Tampa', 'VT', 523544089);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annabell', 'Achille', 6, '7262 Bridge St. Baltimore', 'Philadelphia', 'IL', 810997273);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annabelle', 'Achilles', 80, '657 Cleveland St. Kennewick', 'San Francisco', 'RI', 994219433);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annalee', 'Achin', 69, '32 Woodside St. Hallandale', 'Albuquerque', 'WV', 748894793);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annalisa', 'Achor', 35, '16 Hilltop Street Rockledge', 'Austin', 'LA', 301619765);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annamae', 'Achord', 79, '128 Sierra Lane Encino', 'Scottsdale', 'TN', 485912396);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annamaria', 'Achorn', 30, '7365 East Ivy Street Cockeysville', 'Reno', 'IL', 700027283);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annamarie', 'Achter', 66, '11 East Woodland Lane Elizabeth City', 'Oakland', 'VA', 758838261);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anne', 'Achterhof', 75, '7770 North Marlborough Street Middle River', 'Portland', 'WI', 624212725);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anneliese', 'Achzet', 98, '9138 Winchester Ave. Raleigh', 'Minneapolis', 'RI', 986416454);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annelle', 'Achziger', 37, '507 Piper Rd. Clayton', 'Miami', 'NH', 275720592);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annemarie', 'Acierno', 12, '220 Richardson Avenue Jamaica Plain', 'Birmingham', 'GA', 510559187);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annett', 'Acimovic', 5, '68 Lancaster St. Nottingham', 'Mesa', 'KS', 918694827);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annetta', 'Ack', 58, '7351 N. School Lane Fairburn', 'North Hempstead', 'MT', 296698220);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annette', 'Ackah', 72, '9873 Leeton Ridge Dr. Bel Air', 'San Francisco', 'MD', 641369194);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annice', 'Acken', 56, '8132 Manor Avenue Haines City', 'Minneapolis', 'WA', 536226302);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annie', 'Acker', 31, '5 Howard Dr. Abingdon', 'El Paso', 'MT', 316947652);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annika', 'Ackerley', 54, '441 Gulf Ave. Stuart', 'Baton Rouge', 'WI', 690951119);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annis', 'Ackerly', 2, '33 Nichols Road Roslindale', 'Chandler', 'NH', 286349383);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annita', 'Ackerman', 18, '37 South Rock Maple Road Ontario', 'Boston', 'WY', 144068537);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Annmarie', 'Ackermann', 4, '70 Oakland Street Banning', 'Stockton', 'WV', 393386042);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anthony', 'Ackers', 99, '44 High Ridge St. Feasterville Trevose', 'Tampa', 'SC', 216995308);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anthony', 'Ackerson', 11, '8490 N. Thorne St. Dunedin', 'Lexington-Fayette', 'MI', 972429387);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Antione', 'Ackert', 10, '338 Arcadia Ave. Lake Zurich', 'Lexington-Fayette', 'MT', 123604486);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Antionette', 'Ackies', 92, '7328 East Kirkland Drive Green Bay', 'Tulsa', 'ND', 981327887);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Antoine', 'Ackins', 95, '991 West Dr. Brookfield', 'Raleigh', 'NV', 843653580);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Antoinette', 'Ackison', 60, '9160 Iroquois Lane Middleton', 'Akron', 'NV', 654838198);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anton', 'Ackiss', 83, '8256 Henry Avenue Rego Park', 'New Orleans', 'ND', 410200403);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Antone', 'Ackland', 65, '7520 Hamilton Ave. Jupiter', 'Boston', 'ME', 432365105);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Antonetta', 'Acklen', 64, '7592 Tower St. Hixson', 'Dallas', 'NM', 170534114);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Antonette', 'Ackles', 52, '330 W. Shore St. Helena', 'Corpus Christi', 'VA', 365254563);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Antonia', 'Ackley', 32, '724 Nut Swamp Lane Baldwin', 'Lexington-Fayette', 'KS', 188853692);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Antonia', 'Acklin', 60, '9198 South Pineknoll Road Navarre', 'Arlington', 'SC', 295065859);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Antonietta', 'Ackman', 14, '71 Cobblestone Ave. Owatonna', 'Milwaukee', 'MI', 584949460);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Antonina', 'Ackmann', 96, '473 Old Academy Dr. Winter Haven', 'St. Paul', 'ID', 417810304);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Antonio', 'Ackroyd', 52, '753 E. Shore Lane Newburgh', 'Detroit', 'SC', 142048597);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Antonio', 'Acly', 72, '8421 Annadale Dr. Torrance', 'Omaha', 'KY', 303338480);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Antony', 'Acoba', 59, '62 Van Dyke St. Montgomery Village', 'Wichita', 'MT', 644834163);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Antwan', 'Acocella', 58, '74 Laurel Court Fairfield', 'Denver', 'MO', 994088504);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Anya', 'Acock', 81, '7413 Lafayette Street Altamonte Springs', 'Boise', 'SC', 724854784);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Apolonia', 'Acoff', 5, '7415 Union Drive Mesa', 'Minneapolis', 'OK', 558888701);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('April', 'Acor', 81, '7046 Van Dyke Avenue Grandville', 'Newark', 'SC', 615597728);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Apryl', 'Acord', 7, '7763 Church Ave. Santa Cruz', 'Santa Ana', 'PA', 584178942);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ara', 'Acorda', 0, '88 Hudson Ave. Point Pleasant Beach', 'Fort Wayne', 'PA', 286836817);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Araceli', 'Acors', 99, '129 S. Walt Whitman Drive Chapel Hill', 'Lincoln', 'NE', 995926571);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aracelis', 'Acosta', 57, '46 Walnut Street Oak Lawn', 'Buffalo', 'VA', 579334682);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aracely', 'Acosto', 44, '823 Virginia Drive Arlington Heights', 'St. Louis', 'CT', 889831390);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arcelia', 'Acothley', 86, '74 Virginia Ave. Ravenna', 'Omaha', 'NH', 950636922);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Archie', 'Acquaviva', 94, '902 Shady Rd. Tullahoma', 'Pittsburgh', 'VT', 807990470);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ardath', 'Acquilla', 84, '489 Rock Maple Court Lockport', 'Oklahoma City', 'NC', 997670324);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ardelia', 'Acre', 39, '8970 Essex Ave. Winchester', 'Norfolk', 'ID', 351317750);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ardell', 'Acree', 94, '9655 Pilgrim Street Massillon', 'Austin', 'OK', 897273438);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ardella', 'Acres', 9, '67 Tallwood Lane Metairie', 'El Paso', 'NJ', 241390161);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ardelle', 'Acrey', 9, '9196 South Fremont Court Fullerton', 'Jersey City', 'VA', 755607300);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arden', 'Acri', 24, '9479 Newcastle Ave. Newport News', 'Henderson', 'LA', 226588354);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ardis', 'Acron', 85, '7350 Devon Ave. Mount Airy', 'Kansas City', 'GA', 514324805);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ardith', 'Actis', 22, '8685 Marconi Court Elmont', 'Lubbock', 'WY', 755043656);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aretha', 'Acton', 85, '268 Oklahoma St. Owosso', 'Virginia Beach', 'GA', 365725646);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Argelia', 'Acuff', 43, '7210 SE. Wrangler St. Wilmington', 'Las Vegas', 'AR', 296390646);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Argentina', 'Acuna', 21, '130 Race Avenue New Kensington', 'Colorado Springs', 'AZ', 152554570);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ariana', 'Acy', 32, '8534 East Sulphur Springs Ave. Roswell', 'Modesto', 'MI', 180027768);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ariane', 'Ada', 1, '8528 6th Court Waterbury', 'Long Beach', 'RI', 415257123);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arianna', 'Adachi', 74, '7248 Homestead Ave. Chambersburg', 'Bakersfield', 'IN', 449759510);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arianne', 'Adair', 24, '7277 Plumb Branch Rd. Mishawaka', 'Anchorage', 'ME', 197462779);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arica', 'Adalja', 54, '376 St Paul St. Terre Haute', 'Omaha', 'AK', 688729671);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arie', 'Adam', 8, '8839 Monroe Street Patchogue', 'Denver', 'NY', 553449582);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ariel', 'Adamaitis', 65, '971 Prince Ave. Avon Lake', 'Kansas City', 'IL', 242854132);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ariel', 'Adamcik', 0, '7887 Thomas Street Utica', 'Fort Wayne', 'NM', 256562543);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arielle', 'Adamczak', 16, '7378 Van Dyke Ave. Cincinnati', 'Los Angeles', 'KS', 489035209);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arla', 'Adamczyk', 81, '780 Depot Drive Hallandale', 'Minneapolis', 'NY', 174241524);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arlean', 'Adame', 72, '764 Oak Meadow Street Bettendorf', 'Newark', 'GA', 760111035);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arleen', 'Adamec', 18, '547 East Rocky River Avenue Wellington', 'Rochester', 'UT', 111472297);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arlen', 'Adamek', 46, '5 New Rd. Oxford', 'Laredo', 'FL', 838553026);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arlena', 'Adames', 18, '9360 Pheasant St. Clarkston', 'Modesto', 'NY', 656352689);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arlene', 'Adami', 1, '24 West Clay Circle Griffin', 'St. Paul', 'IA', 548364278);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arletha', 'Adamiak', 49, '9302 Myers Lane Solon', 'Wichita', 'MS', 436428434);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arletta', 'Adamik', 59, '139 Smith Dr. Boynton Beach', 'Fresno', 'CT', 934359642);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arlette', 'Adamis', 11, '424 Big Rock Cove St. Front Royal', 'Arlington', 'OR', 905220623);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arlie', 'Adamitis', 47, '353 Stillwater Ave. Blackwood', 'Cleveland', 'MT', 249078852);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arlinda', 'Adamo', 87, '902 Acacia Street Forest Hills', 'Madison', 'TX', 297911036);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arline', 'Adamos', 77, '634 Philmont Court Rosedale', 'Portland', 'OK', 998738629);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arlyne', 'Adamowski', 36, '21 River St. North Attleboro', 'St. Louis', 'WY', 934813585);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Armand', 'Adams', 63, '9292 Hudson Lane York', 'Durham', 'WA', 907901549);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Armanda', 'Adamsen', 83, '123 SW. Jennings St. Billings', 'Scottsdale', 'AK', 546290365);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Armandina', 'Adamski', 78, '540 North Stonybrook Street Dearborn', 'Dallas', 'NC', 563274683);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Armando', 'Adamsky', 75, '554 North Forest Lane Tampa', 'Scottsdale', 'SD', 137012433);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Armida', 'Adamson', 73, '7439 Division Drive Torrance', 'San Jose', 'TN', 760250502);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arminda', 'Adamsonis', 32, '46 South Court Dr. Graham', 'Chandler', 'WV', 601397350);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arnetta', 'Adamyan', 27, '19 Warren Street Cockeysville', 'Boise', 'KY', 714566100);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arnette', 'Adan', 37, '895 Clinton Lane San Angelo', 'Las Vegas', 'CT', 555548377);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arnita', 'Adank', 100, '9689 Sheffield Ave. Berwyn', 'Toledo', 'PA', 145263685);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arnold', 'Adas', 100, '8206 Forest St. Traverse City', 'Seattle', 'OR', 757861279);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arnoldo', 'Adauto', 1, '7111 La Sierra Ave. Lemont', 'San Diego', 'CO', 312551713);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arnulfo', 'Adaway', 55, '65 Linda Street Mount Prospect', 'Lubbock', 'TX', 854842672);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aron', 'Aday', 30, '108 Rockaway Street Auburndale', 'Long Beach', 'NE', 584137380);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arron', 'Adcock', 9, '23 Bohemia Rd. Toms River', 'St. Paul', 'MA', 884373323);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Art', 'Adcox', 7, '92 Brook St. Los Banos', 'Tucson', 'MA', 210239117);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arthur', 'Addair', 96, '465 Summerhouse Street Melbourne', 'Chandler', 'NH', 832415290);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arthur', 'Addams', 62, '92 Harvey Street Whitehall', 'Boise', 'VT', 200873051);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Artie', 'Addario', 5, '2 Hillside Court Upper Darby', 'San Antonio', 'HI', 388366370);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arturo', 'Addeo', 95, '941 Fawn Drive Clover', 'Columbus', 'GA', 715341385);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Arvilla', 'Adderley', 100, '315 Plymouth Drive Long Beach', 'Anchorage', 'NY', 625996170);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Asa', 'Adderly', 7, '8 Country St. Farmingdale', 'Chandler', 'NH', 978038233);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Asha', 'Addesso', 17, '8209 Walnut Street Decatur', 'Pittsburgh', 'ND', 253593473);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ashanti', 'Addicks', 60, '8 Studebaker Road Danbury', 'Plano', 'MO', 905558604);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ashely', 'Addie', 11, '194 Helen Avenue Queensbury', 'Oklahoma City', 'HI', 830234179);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ashlea', 'Addiego', 54, '975 Edgewater St. Parkersburg', 'Pittsburgh', 'HI', 128829423);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ashlee', 'Addington', 90, '966 Virginia Dr. Orland Park', 'Nashville-Davidson', 'MO', 611094391);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ashleigh', 'Addis', 76, '7903 Lakeshore Drive Ravenna', 'Phoenix', 'MN', 562046684);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ashley', 'Addison', 22, '7862 Euclid Lane Alabaster', 'Wichita', 'VA', 572962443);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ashley', 'Addleman', 53, '309 Wayne Ave. Easley', 'Hialeah', 'MO', 945802541);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ashli', 'Addo', 22, '17 Golf Dr. Bay City', 'Hialeah', 'AL', 215246173);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ashlie', 'Adduci', 77, '440 Fairview Street Omaha', 'Lubbock', 'FL', 175737503);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ashly', 'Addy', 51, '55 Middle River St. Tucson', 'Tampa', 'IA', 163491015);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ashlyn', 'Ade', 5, '9718 South Durham Lane Huntersville', 'Glendale', 'MT', 198478248);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ashton', 'Adebisi', 38, '7054 Rocky River Street Levittown', 'Montgomery', 'ID', 241609486);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Asia', 'Adee', 70, '7920 Newbridge Dr. Garden City', 'Santa Ana', 'MT', 787759005);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Asley', 'Adel', 84, '8061 Thorne Ave. Forney', 'Birmingham', 'MS', 374609840);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Assunta', 'Adelblue', 93, '63 Lees Creek Court Greenwood', 'Plano', 'NM', 884075068);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Astrid', 'Adelgren', 3, '8169 Applegate St. Davison', 'Chicago', 'GA', 399060896);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Asuncion', 'Adelizzi', 87, '8849 Miles Drive Olive Branch', 'Phoenix', 'MI', 582310441);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Athena', 'Adell', 16, '444 Rockville Dr. Zeeland', 'St. Petersburg', 'NY', 310712464);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aubrey', 'Adelman', 5, '9019 Delaware Street Dekalb', 'Seattle', 'CO', 855297188);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aubrey', 'Adelmann', 4, '905 Arch Street Hendersonville', 'Seattle', 'PA', 582156058);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Audie', 'Adelmund', 19, '172 Bridgeton Ave. Wilmington', 'Phoenix', 'CO', 737269105);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Audra', 'Adels', 82, '9277 6th Rd. Waltham', 'Omaha', 'NH', 182652678);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Audrea', 'Adelsberg', 79, '29 E. Airport St. Rolla', 'Jersey City', 'NE', 225226269);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Audrey', 'Adelson', 37, '41 Valley Farms Avenue Saginaw', 'Lexington-Fayette', 'HI', 187575930);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Audria', 'Adelsperger', 58, '3 Lees Creek Ave. Nanuet', 'Scottsdale', 'IN', 237252049);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Audrie', 'Adelstein', 31, '9311 North Oklahoma Street Hillsboro', 'North Hempstead', 'RI', 391978347);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Audry', 'Adema', 98, '613 Locust St. Mansfield', 'San Francisco', 'FL', 320961977);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('August', 'Aden', 77, '135 North Plymouth Ave. Ossining', 'Fort Wayne', 'NJ', 136196645);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Augusta', 'Adens', 95, '8330 Hudson Rd. Roseville', 'Riverside', 'ID', 323210753);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Augustina', 'Ader', 40, '598 North North Street Roanoke Rapids', 'Arlington', 'WI', 471620070);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Augustine', 'Aderhold', 44, '344 Arnold Ave. Downers Grove', 'Indianapolis', 'AK', 851937602);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Augustine', 'Aderholdt', 62, '707 West Rd. Lake Villa', 'San Bernardino', 'VT', 413665093);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Augustus', 'Aderholt', 96, '499 Nichols Court Kennesaw', 'Akron', 'RI', 481255238);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aundrea', 'Aderman', 74, '372 East Cherry Street Sylvania', 'Milwaukee', 'IL', 674764371);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aura', 'Aderson', 75, '8286 East Ridgeview Road Staten Island', 'Madison', 'AR', 723617639);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aurea', 'Ades', 26, '7472 Rosewood Rd. Jamaica', 'North Hempstead', 'KS', 440909162);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aurelia', 'Adessa', 46, '73 Wentworth Street Glasgow', 'Montgomery', 'MS', 507545756);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aurelio', 'Adesso', 37, '7549 Mayfield Street New Castle', 'Aurora', 'MA', 158719654);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aurora', 'Adey', 26, '182 N. Smoky Hollow Lane Lincoln', 'Columbus', 'ME', 421158175);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Aurore', 'Adeyemo', 51, '7223 Garfield Dr. Holyoke', 'San Jose', 'NM', 391895057);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Austin', 'Adger', 0, '802 Fulton St. Logansport', 'El Paso', 'NE', 543393050);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Austin', 'Adham', 76, '36 Grant Dr. Baldwin', 'North Hempstead', 'NH', 933242762);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Autumn', 'Adhami', 70, '18 Brandywine Dr. Ocean Springs', 'Garland', 'CT', 169849460);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ava', 'Adi', 40, '96 Union Dr. Bristol', 'Long Beach', 'MA', 543369222);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Avelina', 'Adib', 1, '56 Border Circle Mableton', 'Montgomery', 'SC', 854469684);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Avery', 'Adickes', 21, '52 Bay Meadows Ave. Douglasville', 'Indianapolis', 'MS', 968557235);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Avery', 'Adie', 4, '8783 Dogwood Ave. Tuckerton', 'Lincoln', 'SD', 878752635);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Avis', 'Adil', 87, '22 Holly Road Roseville', 'Boise', 'WY', 553935147);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Avril', 'Adinolfi', 6, '92 Pennington Dr. Niagara Falls', 'Hialeah', 'TN', 827571820);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Awilda', 'Adjei', 63, '7021 Arlington Dr. Lumberton', 'Boston', 'WI', 432786604);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ayako', 'Adjutant', 48, '7413 Heritage Ave. Fair Lawn', 'Milwaukee', 'NH', 230040709);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ayana', 'Adkerson', 40, '9384 Shirley St. Painesville', 'New Orleans', 'CA', 740630498);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ayanna', 'Adkin', 29, '677 East Ridge Rd. Davison', 'Stockton', 'SD', 757793530);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ayesha', 'Adkins', 74, '618 West Heather Ave. Reading', 'Lincoln', 'MT', 505157805);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Azalee', 'Adkinson', 2, '405 Nut Swamp Ave. Flushing', 'Chicago', 'RI', 247481019);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Azucena', 'Adkison', 43, '15 Richardson St. Albany', 'Indianapolis', 'SD', 516446049);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Azzie', 'Adkisson', 76, '8243 Thompson Court Danbury', 'Rochester', 'UT', 308622297);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Babara', 'Adlam', 76, '7373 Woodsman Street Gurnee', 'Anaheim', 'LA', 989585348);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Babette', 'Adle', 62, '9445 Livingston Drive Valrico', 'Dallas', 'TX', 620527722);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bailey', 'Adleman', 18, '857 S. Poplar Street Jenison', 'Aurora', 'ND', 807361880);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bambi', 'Adler', 29, '9658 Tunnel Dr. Winchester', 'Rochester', 'DE', 189734309);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bao', 'Adley', 59, '34 Market Ave. Rome', 'Atlanta', 'SD', 315888143);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Barabara', 'Adling', 90, '872 Wild Horse Street Frankfort', 'San Bernardino', 'MT', 242548789);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Barb', 'Adloff', 36, '85 Somerset Street Honolulu', 'St. Petersburg', 'NY', 228347195);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Barbar', 'Admas', 95, '74 North Branch Street Williamsburg', 'Mesa', 'ME', 738333991);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Barbara', 'Admire', 25, '62 Stillwater Dr. Round Lake', 'Fresno', 'NH', 566321000);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Barbera', 'Adner', 87, '9734 Andover St. Strongsville', 'Kansas City', 'VA', 728564575);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Barbie', 'Adney', 74, '39 Constitution Street Halethorpe', 'San Diego', 'AK', 969272992);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Barbra', 'Adolf', 95, '96 Carriage Ave. Schaumburg', 'Montgomery', 'SD', 639180111);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bari', 'Adolfo', 8, '91 Maiden Road Hope Mills', 'Glendale', 'MA', 630701478);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Barney', 'Adolfson', 50, '66 Brook St. Hinesville', 'Portland', 'HI', 494289603);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Barrett', 'Adolph', 58, '372 Purple Finch Ave. Conyers', 'Denver', 'LA', 330488922);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Barrie', 'Adolphe', 77, '8 County St. Lincoln Park', 'Virginia Beach', 'AL', 623237470);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Barry', 'Adolphsen', 2, '954 Arlington Dr. Avon Lake', 'Oakland', 'IL', 832272720);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bart', 'Adolphson', 42, '9108 E. Nicolls Drive Chandler', 'Laredo', 'IA', 990479888);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Barton', 'Adolphus', 19, '937 Dogwood Dr. West Bloomfield', 'Tampa', 'NY', 905873512);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Basil', 'Adomaitis', 90, '9 S. Hamilton St. North Fort Myers', 'Newark', 'NY', 171866040);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Basilia', 'Adon', 60, '4 South Green Avenue Palatine', 'Aurora', 'FL', 549784960);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bea', 'Adonis', 2, '653 Cobblestone St. Chardon', 'El Paso', 'AR', 663465300);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Beata', 'Adorno', 0, '9213 Peg Shop St. Marquette', 'Lubbock', 'FL', 158863722);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Beatrice', 'Adragna', 87, '20 Foster Ave. Hagerstown', 'Atlanta', 'NH', 816310492);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Beatris', 'Adrian', 44, '261 Pacific St. Morrisville', 'St. Louis', 'MT', 598734527);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Beatriz', 'Adriance', 81, '206 Nut Swamp Ave. Oak Forest', 'Durham', 'TN', 431292896);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Beau', 'Adriano', 59, '54 Roberts St. Yakima', 'Las Vegas', 'ME', 486389875);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Beaulah', 'Adrid', 89, '2 South Drive Wausau', 'Baltimore', 'CA', 272414808);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bebe', 'Adrien', 28, '51 Sycamore Drive Oak Ridge', 'Boise', 'VA', 133969237);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Becki', 'Adrion', 84, '898 Livingston Drive Grovetown', 'Baton Rouge', 'NE', 518922516);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Beckie', 'Adrovel', 4, '74 Brookside Street Santa Clara', 'Chesapeake', 'UT', 180818959);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Becky', 'Adside', 0, '643 Mayfair Lane Lakeville', 'Anchorage', 'OK', 822914208);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bee', 'Adsit', 29, '8033 Edgewater St. Tucson', 'Arlington', 'DE', 713519548);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Belen', 'Adu', 81, '9029 Vine Ave. Elk River', 'San Diego', 'FL', 308556659);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Belia', 'Aduddell', 83, '73 Maple Lane Omaha', 'St. Louis', 'MS', 971668070);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Belinda', 'Adule', 95, '55 Morris Ave. Pittsford', 'Minneapolis', 'MS', 492830029);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Belkis', 'Adwell', 5, '7441 Fifth Drive Batavia', 'Boise', 'HI', 636135564);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bell', 'Ady', 63, '231 Edgemont Ave. Millington', 'Newark', 'VA', 415049382);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bella', 'Adzhabakyan', 20, '33 El Dorado Street Jacksonville Beach', 'Long Beach', 'RI', 490170753);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Belle', 'Aegerter', 26, '38 East Pleasant Circle Poughkeepsie', 'Fort Worth', 'ND', 128953535);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Belva', 'Aeillo', 37, '9859 Gartner Dr. Derby', 'Tulsa', 'MN', 609292058);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Ben', 'Aeling', 25, '83 Marvon Lane Louisville', 'Oklahoma City', 'SC', 499563709);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Benedict', 'Aemmer', 87, '96 Cooper St. Westfield', 'Jacksonville', 'DE', 369047173);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Benita', 'Aerni', 74, '636 Birchwood St. Glendora', 'Boise', 'NV', 625179810);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Benito', 'Aerts', 55, '77 Green Ave. Gulfport', 'Sacramento', 'NV', 189480536);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Benjamin', 'Aery', 90, '853 Birch Hill Ave. Elyria', 'North Hempstead', 'NJ', 746038174);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bennett', 'Aeschbacher', 75, '916 Rockwell Street Everett', 'Aurora', 'KS', 826885503);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bennie', 'Aeschliman', 59, '856 Ridge Dr. Newton', 'Huntington', 'NE', 526398510);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bennie', 'Aeschlimann', 65, '58 Madison Lane Chaska', 'Baltimore', 'MI', 595730467);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Benny', 'Afable', 57, '531 Forest St. Redford', 'Cincinnati', 'CO', 282345713);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Benton', 'Afalava', 18, '898 Philmont Court Orchard Park', 'Phoenix', 'SD', 648820107);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Berenice', 'Afan', 70, '195 S. Hillcrest St. Ottumwa', 'Los Angeles', 'ME', 910659216);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Berna', 'Afanador', 16, '11 Stillwater St. Grovetown', 'Chicago', 'OH', 382587946);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bernadette', 'Affagato', 79, '58 Santa Clara Rd. Elmhurst', 'Birmingham', 'SC', 878106901);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bernadine', 'Affeld', 57, '241 Gonzales St. Anaheim', 'Chandler', 'SC', 758926823);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bernard', 'Affelt', 57, '7128 Bridle Street West Lafayette', 'Indianapolis', 'CA', 449847445);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bernarda', 'Affeltranger', 20, '66 Newport Road Gaithersburg', 'Newark', 'AR', 855730123);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bernardina', 'Affleck', 83, '50 Sunbeam Ave. Paramus', 'Baltimore', 'AL', 967261742);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bernardine', 'Afflick', 14, '95 Taylor Street Drexel Hill', 'Virginia Beach', 'AK', 137830589);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bernardo', 'Affolter', 19, '6 Pineknoll St. Astoria', 'Arlington', 'CA', 727770405);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Berneice', 'Affronti', 89, '759 Summerhouse Lane Gainesville', 'Bakersfield', 'NC', 519197108);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bernetta', 'Aflalo', 18, '4 Madison Lane Banning', 'Akron', 'CT', 297848480);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bernice', 'Afoa', 69, '246 Sunbeam Road Statesville', 'Los Angeles', 'TX', 492104734);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bernie', 'Afonso', 15, '8195 Orange Dr. Utica', 'Oklahoma City', 'TX', 305210142);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bernie', 'Africa', 9, '357 Devon St. Grayslake', 'Greensboro', 'KS', 324965093);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Berniece', 'Afshar', 83, '3 Water Lane Maryville', 'Laredo', 'MN', 390846791);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bernita', 'Afshari', 52, '8086 East Lower River St. East Orange', 'Milwaukee', 'SD', 500429233);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Berry', 'Afton', 85, '482 Elm Ave. Blacksburg', 'Pittsburgh', 'AL', 200235637);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Berry', 'Afurong', 31, '779 Lawrence St. Marion', 'Detroit', 'KY', 291637311);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bert', 'Afzal', 4, '8285 Bridle St. Muskego', 'Laredo', 'DE', 499827183);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Berta', 'Agamao', 55, '8954 Trout Street Elmhurst', 'Oakland', 'DE', 978237465);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bertha', 'Agan', 40, '8850 Beechwood Street Reston', 'Riverside', 'MS', 922422538);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bertie', 'Agans', 53, '774 Rosewood Ave. Wadsworth', 'Oakland', 'LA', 917942850);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bertram', 'Agar', 63, '41 Buttonwood St. Germantown', 'El Paso', 'TX', 327647830);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Beryl', 'Agard', 33, '8757 Belmont St. Fort Washington', 'Arlington', 'UT', 695219394);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bess', 'Agarwal', 55, '8869 N. Wood Ave. Snohomish', 'Mesa', 'CT', 416975049);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bessie', 'Agbayani', 71, '522 Bow Ridge St. Sidney', 'Long Beach', 'RI', 598670993);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Beth', 'Agbisit', 12, '749 Fairfield St. Wooster', 'Aurora', 'NV', 980703080);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bethanie', 'Agcaoili', 36, '79 Shipley St. Clermont', 'Lubbock', 'VT', 998901597);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bethann', 'Age', 55, '97 Devon Rd. Malvern', 'Garland', 'WV', 860186296);
INSERT INTO Customers(FirstName,LastName,Age,Street,City,State,PhoneNumber) VALUES('Bethany', 'Ageboi', 97, '47 Pulaski Lane Brookline', 'Las Vegas', 'MI', 884722335);

